import { articleFactory, details, steps } from './types';
const t = articleFactory('team');
const r = articleFactory('roles');
export const teamArticles = [
  t('viewing-users', 'Viewing Users', 'Review workspace members in Team Management.', [steps('Open Settings → Team Management.', 'Open the Users area and review names, emails, roles, statuses, and groups.', 'Search or filter to find a specific member.')], { notes: ['User administration requires the relevant user-management permissions. Available controls depend on your role.'], related: ['filtering-users', 'user-roles'] }),
  t('creating-users', 'Creating a User', 'Add an authorized team member to the workspace.', [steps('Open Settings → Team Management → Users and choose New User.', 'Enter First Name, Last Name, the employee email username, and a required Philippine mobile Phone number. The form supplies the employee email domain.', 'Choose an active custom Role. Job Title is optional; Client Admin can select existing Groups.', 'Select Create User and check the saved member and setup-email status.')], { notes: ['Creating a user requires user creation and role assignment access. A Phone number is required: enter the 10 mobile digits starting with 9 after +63.', 'Group membership is administrator-managed and optional. An ordinary user cannot grant themselves membership or administrator access.'], related: ['user-roles'], keywords: ['create', 'add', 'member'] }),
  t('user-status', 'User Status', 'Review enabled accounts and safely change their access.', [details('Status values', 'Active identifies an enabled account; password setup and onboarding can still be required before CRM access.', 'Inactive identifies a disabled account. Supported status changes are Active and Inactive.'), steps('Find the member in Team Management → Users.', 'Client Admin can choose Deactivate and review assigned records and unfinished Tasks before confirming. Choose Activate to enable an inactive account.', 'Review the saved status and the resulting assignment history.')], { notes: ['You cannot deactivate yourself, and at least one active Client Admin must remain.'], related: ['archiving-users'] }),
  t('groups', 'Groups', 'Manage the same groups used by workflow assignment.', [steps('Create or edit the user in Team Management.', 'Select existing Groups on the user form, or manage members in Team Management → Groups.', 'Save Changes.')], { notes: ['Client Admin manages multiple Group memberships. Save an empty selection to remove all memberships.', 'Activate an inactive user before changing their memberships. Existing memberships remain visible while inactive.', 'Groups feed the same Workflow assignment pools; roles still control module permissions. Profile displays Groups read-only.'], related: ['user-roles', 'profile-settings'] }),
  t('archiving-users', 'Deactivating and Archiving Users', 'Transfer unfinished work before removing a member’s access.', [steps('Find the member in Team Management → Users.', 'Client Admin chooses Deactivate. Review Leads, Contacts, Accounts, Deals, and unfinished Tasks in Reassign Records and Tasks.', 'When work exists, choose another eligible active Assigned Agent. A replacement receiving unfinished Tasks must also have Tasks View access.', 'Continue and confirm Deactivate. Ownership transfers, assignment activity, audit history, and account deactivation commit together.', 'Use Archive only after assigned work has been cleared; restore an eligible inactive user from Archived Data when needed.')], { notes: ['Completed, cancelled, and archived Tasks keep their historical assignee. Sessions are revoked when the user is deactivated.', 'Archive requires user archive access and rejects remaining assigned records or unfinished Tasks. It does not select a replacement automatically.'], related: ['user-status', 'assigning-leads', 'assigning-tasks'] }),
  t('filtering-users', 'Filtering Users', 'Find team members by query, role, status, or Group.', [steps('Open Team Management → Users.', 'Search for the member and choose Role, Status, or Group filters.', 'Use Archived Data to review inactive members when you have the required access.', 'Clear filters to return to the full available list.')], { related: ['viewing-users', 'exporting-users'] }),
  t('exporting-users', 'User Export Availability', 'Review team information using the current Users list.', [steps('Open Settings → Team Management → Users.', 'Apply search, role, status, or Group filters to find the members you need.', 'Open a member to review their saved profile and memberships.')], { notes: ['The current Users screen has no CSV export control. Available member information remains subject to your user-management permissions.'], related: ['filtering-users', 'viewing-users'], keywords: ['csv', 'download', 'export'] }),
  t('user-roles', 'Understanding User Roles', 'Roles determine the actions a user can perform in the workspace.', [details('Access and profile information', 'A user’s assigned role grants module capabilities such as view, create, edit, and archive/delete.', 'A job title or group membership does not replace role permissions.', 'Client Admin manages the workspace; custom roles can grant a narrower set of capabilities.')], { related: ['understanding-roles', 'assigning-roles', 'permission-denied'] }),
];
export const roleArticles = [
  r('understanding-roles', 'Understanding Roles', 'Control team access with system and custom roles.', [details('How access works', 'Module permissions determine whether users can view, create, edit, or archive records. Some modules expose additional capabilities.', 'Leads, Contacts, Accounts, and Tasks have independent module permissions. Grant the capabilities needed for each job.', 'The server enforces access in addition to the controls shown in the interface. Seeing documentation does not grant permission to perform an action.')], { related: ['system-custom-roles', 'assigning-permissions', 'permission-denied'] }),
  r('system-custom-roles', 'System Roles vs Custom Roles', 'Use protected system roles or define a narrower custom role.', [details('Role types', 'System roles provide the built-in access model. Their protected names and permissions cannot be edited like a custom role, and they cannot be deleted.', 'Custom roles let authorized administrators choose specific capabilities.', 'Administrator access cannot be restricted using an ordinary custom-permission toggle. Use a custom role for limited access.')], { related: ['creating-roles', 'role-restrictions'] }),
  r('creating-roles', 'Creating a Custom Role', 'Define a named set of capabilities for your team.', [steps('Open Settings → Roles & Permissions and choose Create Custom Role.', 'Enter a unique Role Name (required, up to 50 characters). Add an optional Description.', 'Review permission groups and enable the intended capabilities.', 'Choose Create Role and verify the saved role.', 'Assign the role to the intended users in Team Management.')], { notes: ['Creating custom roles requires role-management access. Reserved system-role names cannot be reused.'], related: ['assigning-permissions', 'assigning-roles', 'role-problems'], keywords: ['create role', 'new role', 'custom', 'permissions'] }),
  r('assigning-permissions', 'Assigning Permissions', 'Choose the capabilities a custom role grants.', [details('Permission groups', 'Review the named permission groups and their individual module capabilities in the role editor.', 'A group toggle enables or disables the available capabilities represented by that group. Expand the group to inspect individual permissions.', 'A partially enabled group means only some capabilities are selected. Review each permission before saving.'), steps('Create or edit a custom role.', 'Choose the required groups or individual capabilities.', 'Save the role and review the enabled permissions.')], { notes: ['Each action is checked on the server. A view grant does not automatically allow creation, editing, assignment, publishing, sending, or archiving.'], related: ['editing-roles', 'role-restrictions'] }),
  r('editing-roles', 'Editing a Custom Role', 'Update an existing role’s name, description, or access.', [steps('Open Roles & Permissions and the custom role’s menu.', 'Choose Edit.', 'Update the editable fields and permission selections.', 'Select Save Changes.')], { notes: ['Role details and permission selections save together. Changes affect assigned users; their available controls update automatically as access changes are received. System roles remain protected.'], related: ['assigning-permissions', 'assigning-roles'] }),
  r('assigning-roles', 'Assigning Roles to Users', 'Apply an available role through Team Management.', [steps('Open Settings → Team Management → Users.', 'Create a user or edit an existing member.', 'Choose the appropriate Role and save.', 'The member’s available controls update automatically when the current access change is received. Review the saved assignment if the expected access is missing.')], { notes: ['Assigning roles requires role assignment access. Creating a role alone does not assign it to anyone.'], related: ['user-roles', 'creating-roles'] }),
  r('role-restrictions', 'Role Restrictions', 'Understand protected roles and rejected role changes.', [details('Restrictions', 'System roles cannot be renamed, freely modified, or deleted through custom-role controls.', 'Custom role names must be valid and unique in the workspace; reserved system names are not available.', 'Role changes and assignment remain subject to server authorization.', 'Archived custom roles can be restored from Archived Data with the appropriate access.')], { related: ['role-problems', 'system-custom-roles'] }),
];
