import { articleFactory, details, steps } from './types';
const t = articleFactory('team');
const r = articleFactory('roles');
export const teamArticles = [
  t('viewing-users', 'Viewing Users', 'Review workspace members in Team Management.', [steps('Open Settings → Team Management.', 'Open the Users area and review names, emails, roles, statuses, and departments.', 'Search or filter to find a specific member.')], { notes: ['User administration requires the relevant user-management permissions. Available controls depend on your role.'], related: ['filtering-users', 'user-roles'] }),
  t('creating-users', 'Creating a User', 'Add an authorized team member to the workspace.', [steps('Open Settings → Team Management → Users and choose the add-user control.', 'Enter First Name, Last Name, and Email, then choose an available custom role.', 'Add Phone, Job Title, and Department as needed.', 'Select Create User and check the saved member and setup-email status.')], { notes: ['Creating a user requires user creation access and an available custom role. Administrative controls are restricted; an ordinary user cannot grant themselves administrator access.'], related: ['user-roles'], keywords: ['create', 'add', 'member'] }),
  t('user-status', 'User Status', 'Distinguish active, inactive, and pending members.', [details('Status values', 'Active identifies an enabled member.', 'Inactive identifies a disabled member.', 'Pending identifies a member whose account setup is not complete.'), steps('Find the member in Users.', 'If authorized, open Edit and choose the appropriate status.', 'Save Changes and verify the result.')], { related: ['archiving-users'] }),
  t('departments', 'Departments', 'Record a department on a team member’s profile.', [steps('Create or edit the user in Team Management.', 'Enter Department and, if useful, Job Title.', 'Save Changes.')], { notes: ['Department is profile information. Entering a department does not itself grant module permissions.'], related: ['user-roles', 'profile-settings'] }),
  t('archiving-users', 'Archiving Users', 'Remove a member from active team management.', [steps('Find the member in Team Management.', 'Use the available archive action and review its confirmation.', 'Confirm only after checking the member’s current assignments.')], { notes: ['This requires user archive/delete access. Archiving a user should not be treated as automatically reassigning their leads, deals, or tasks.'], related: ['user-status', 'assigning-leads', 'assigning-tasks'] }),
  t('filtering-users', 'Filtering Users', 'Find team members by query, role, or status.', [steps('Open Team Management → Users.', 'Search for the member and choose role or status filters.', 'Use the archived visibility control when investigating archived members.', 'Clear filters to return to the full available list.')], { related: ['viewing-users', 'exporting-users'] }),
  t('exporting-users', 'Exporting Users', 'Download the filtered team list as CSV.', [steps('Open Team Management → Users.', 'Apply the search, role, and status filters you need.', 'Select Export.')], { notes: ['The export includes Name, Email, Role, Status, Phone, and Department. Handle the downloaded team information appropriately.'], related: ['filtering-users', 'viewing-users'], keywords: ['csv', 'download'] }),
  t('user-roles', 'Understanding User Roles', 'Roles determine the actions a user can perform in the workspace.', [details('Access and profile information', 'A user’s assigned role grants module capabilities such as view, create, edit, and archive/delete.', 'A job title or department does not replace role permissions.', 'Client Admin manages the workspace; custom roles can grant a narrower set of capabilities.')], { related: ['understanding-roles', 'assigning-roles', 'permission-denied'] }),
];
export const roleArticles = [
  r('understanding-roles', 'Understanding Roles', 'Control team access with system and custom roles.', [details('How access works', 'Module permissions determine whether users can view, create, edit, or archive records. Some modules expose additional capabilities.', 'Lead access uses contact permissions. Accounts have their own permissions.', 'The server enforces access in addition to the controls shown in the interface. Seeing documentation does not grant permission to perform an action.')], { related: ['system-custom-roles', 'assigning-permissions', 'permission-denied'] }),
  r('system-custom-roles', 'System Roles vs Custom Roles', 'Use protected system roles or define a narrower custom role.', [details('Role types', 'System roles provide the built-in access model. Their protected names and permissions cannot be edited like a custom role, and they cannot be deleted.', 'Custom roles let authorized administrators choose specific capabilities.', 'Administrator access cannot be restricted using an ordinary custom-permission toggle. Use a custom role for limited access.')], { related: ['creating-roles', 'role-restrictions'] }),
  r('creating-roles', 'Creating a Custom Role', 'Define a named set of capabilities for your team.', [steps('Open Settings → Roles & Permissions and choose Create Custom Role.', 'Enter a unique Role Name (required, up to 50 characters). Add an optional Description.', 'Review permission groups and enable the intended capabilities.', 'Choose Create Role and verify the saved role.', 'Assign the role to the intended users in Team Management.')], { notes: ['Creating custom roles requires role-management access. Reserved system-role names cannot be reused.'], related: ['assigning-permissions', 'assigning-roles', 'role-problems'], keywords: ['create role', 'new role', 'custom', 'permissions'] }),
  r('assigning-permissions', 'Assigning Permissions', 'Choose the capabilities a custom role grants.', [details('Permission groups', 'Organization; Contacts & Accounts; Deals & Pipeline; Workflows & Automation; Marketing & Campaigns; Reports & Analytics; Dashboard.', 'A group toggle enables or disables the available capabilities represented by that group. Expand the group to inspect individual permissions.', 'A partially enabled group means only some capabilities are selected. Review each permission before saving.'), steps('Create or edit a custom role.', 'Choose the required groups or individual capabilities.', 'Save the role and review the enabled permissions.')], { notes: ['A permission’s presence does not guarantee that every associated product feature is finished. For example, campaign sending still has delivery limitations.'], related: ['editing-roles', 'role-restrictions'] }),
  r('editing-roles', 'Editing a Custom Role', 'Update an existing role’s name, description, or access.', [steps('Open Roles & Permissions and the custom role’s menu.', 'Choose Edit.', 'Update the editable fields and permission selections.', 'Select Save Changes.')], { notes: ['Changes affect users assigned to the role. System roles remain protected.'], related: ['assigning-permissions', 'assigning-roles'] }),
  r('assigning-roles', 'Assigning Roles to Users', 'Apply an available role through Team Management.', [steps('Open Settings → Team Management → Users.', 'Create a user or edit an existing member.', 'Choose the appropriate Role and save.', 'Ask the member to refresh their session if recently changed access is not yet reflected.')], { notes: ['Assigning roles requires authorized user-management access. Creating a role alone does not assign it to anyone.'], related: ['user-roles', 'creating-roles'] }),
  r('role-restrictions', 'Role Restrictions', 'Understand protected roles and rejected role changes.', [details('Restrictions', 'System roles cannot be renamed, freely modified, or deleted through custom-role controls.', 'Custom role names must be valid and unique in the workspace; reserved system names are not available.', 'Role changes and assignment remain subject to server authorization.', 'Archived roles cannot be restored from Archived Data; create an appropriate new role instead.')], { related: ['role-problems', 'system-custom-roles'] }),
];
