import { articleFactory, details, steps } from './types';
const a = articleFactory('campaigns');
const deliveryNote = 'Submitting a message to the provider does not prove delivery. Review the campaign report for confirmed recipient outcomes. If an outcome is uncertain, check provider records before sending again.';
export const campaignArticles = [
  a('campaigns-overview', 'Campaigns Overview', 'Prepare campaigns, select saved audiences, and review recipient delivery.', [details('Available workspace', 'Campaigns includes campaign lists, the message builder, saved target audiences, Email Templates, and SMS Templates.', 'Email campaigns use the configured Brevo sender. SMS campaigns use the configured TextBee gateway.', 'Send Now submits a frozen recipient list and records each provider result in the campaign report.')], { notes: [deliveryNote], related: ['creating-campaigns', 'campaign-delivery', 'email-templates'] }),
  a('creating-campaigns', 'Creating a Campaign', 'Prepare a draft and check its audience before sending.', [steps('Open Campaigns and choose Create Campaign.', 'Enter Campaign Name and choose Email or SMS.', 'Choose the recipient source or a saved target audience, then review eligible and excluded counts.', 'For email, enter a Subject Line; write the content or start from a template.', 'Review the preview and choose Save Draft. Users with sending access can choose Send Now after validation.')], { notes: [deliveryNote], related: ['email-campaigns', 'sms-campaigns', 'target-audiences'], keywords: ['create', 'new', 'draft', 'marketing'] }),
  a('email-campaigns', 'Email Campaigns', 'Send personalized campaign email through the configured sender.', [steps('Choose Email in the campaign builder.', 'Enter the name, subject, content, and target audience.', 'Review the sender and personalized preview, then save the draft or choose Send Now.', 'Open the campaign report to see Submitted, Sent, Delivered, Bounced, Failed, or Pending recipient outcomes.')], { notes: [deliveryNote, 'Your administrator must configure the Brevo sender and delivery receipts. Connected Gmail is used separately for individual CRM and Workflow email.'], related: ['email-templates', 'campaign-delivery'] }),
  a('sms-campaigns', 'SMS Campaigns', 'Send personalized messages through the configured TextBee gateway.', [details('Before sending', 'Your administrator must configure TextBee and an available gateway device.', 'Choose an audience with valid eligible phone numbers. The builder checks the complete personalized message against the SMS length limit.', 'Submission, sending, and delivery are different outcomes. Review recipient results and provider updates in the campaign report.')], { notes: [deliveryNote], related: ['sms-templates', 'campaign-delivery'], keywords: ['text message', 'android', 'gateway', 'delivery'] }),
  a('multi-channel-campaigns', 'Multi-channel Campaigns', 'Understand the draft-only combined message option.', [details('Current availability', 'Multi-channel content can be saved as a draft.', 'Send Now supports Email or SMS. Use a separate campaign for each delivery channel.')], { related: ['email-templates', 'sms-templates', 'campaign-delivery'] }),
  a('target-audiences', 'Understanding Campaign Target Audiences', 'Use saved conditions and review recipient eligibility.', [details('Recipient selection', 'Choose Leads, Contacts, All, or a saved target audience in the builder.', 'Saved audiences keep their conditions in the workspace and are resolved on the server.', 'Review the preview counts and exclusion reasons. Sending resolves the audience again and freezes the eligible recipient list for that campaign.')], { notes: ['A preview can change when CRM records change. The campaign report records the recipients selected when sending began.'], related: ['creating-campaigns', 'campaign-delivery'], keywords: ['recipient', 'segment', 'conditions', 'all contacts'] }),
  a('sms-templates', 'Creating SMS Templates', 'Save reusable text in the SMS template library.', [steps('Open Campaigns → SMS Templates and select New SMS Template.', 'Enter Template Name and choose Category: Marketing, Sales, Onboarding, or Support.', 'Write Message Content and use Insert Variable for a supported placeholder.', 'Select Save Template and verify the saved item.'), details('Supported variables', '{{first_name}}, {{last_name}}, {{company_name}}, {{sender_name}}, and {{sender_email}}.', 'For example: Hi {{first_name}}, thank you for your inquiry.')], { notes: ['Saving a template does not send a message. The complete personalized SMS must fit the length limit when used in a campaign.'], related: ['sms-campaigns', 'email-templates'], keywords: ['create', 'phone', 'placeholder', 'variable', 'text'] }),
  a('email-templates', 'Creating Email Templates', 'Save a reusable subject and message.', [steps('Open Campaigns → Email Templates and select New Email Template.', 'Enter Template Name and Category.', 'Enter Subject Line and Message Content.', 'Use Insert Variable for a supported placeholder.', 'Select Save Template and verify it in the library. Use Preview to inspect it or Use Template to start campaign content.')], { notes: ['Saving a template does not send an email. Review variables and links in the campaign preview before sending.'], related: ['email-campaigns', 'workflow-actions'], keywords: ['create', 'subject', 'body', 'placeholder', 'variable'] }),
  a('scheduling-campaigns', 'Scheduling Campaigns', 'Understand which sending actions are available.', [details('Available actions', 'Campaigns support Save Draft and Send Now; campaign scheduling is not available.', 'Individual Gmail emails can be scheduled from the Inbox composer. Open Scheduled to review or cancel a pending send.', 'After cancellation, the email remains in Drafts for editing. Delivery that has started or needs verification cannot be cancelled.')], { related: ['campaign-statuses', 'campaign-delivery'], keywords: ['schedule', 'date', 'time', 'send later', 'scheduled email'] }),
  a('campaign-metrics', 'Campaign Metrics', 'Read provider evidence and engagement counts.', [details('What the screen shows', 'Submitted counts provider acceptance; Sent and Delivered require provider evidence.', 'Email reports show recorded opens and clicks. Click-through rate uses delivered recipients, and click-to-open rate uses recipients who opened.', 'Historical reports without complete receipt history show unavailable totals rather than invented results.')], { notes: [deliveryNote], related: ['campaign-delivery', 'campaign-statuses'] }),
  a('campaign-statuses', 'Campaign Statuses', 'Read the campaign lifecycle labels.', [details('Status labels', 'Draft is editable preparation. Sending means submission or provider delivery confirmation is still in progress.', 'Interrupted means submission stopped and some results may need review; untouched recipients are recorded as not sent.', 'Sent, Partially Sent, Delivered, and Failed are derived from recipient evidence. A submitted message may still await delivery confirmation.')], { related: ['scheduling-campaigns', 'campaign-metrics'] }),
  a('campaign-delivery', 'Campaign Delivery', 'Review confirmed results and handle interrupted submissions.', [details('Reliable delivery records', 'Sending freezes the audience and records provider attempts before making email or SMS requests.', 'When sending is interrupted, recovery preserves confirmed results, marks untouched recipients as not sent, and leaves uncertain outcomes pending review.', 'Recovery does not automatically replay uncertain sends. Check the report and provider records before deciding whether to create another campaign.', 'Provider receipts can update recipient outcomes and campaign totals after submission finishes.')], { notes: [deliveryNote], related: ['campaign-problems', 'target-audiences'], keywords: ['not sent', 'failed', 'email', 'sms', 'transport', 'interrupted'] }),
];
