import { articleFactory, details, steps } from './types';
const a = articleFactory('campaigns');
const deliveryNote = 'Campaign delivery is not complete in this version. Sending can change a campaign’s status without delivering messages. Do not use a success message or campaign status as proof of recipient delivery.';
export const campaignArticles = [
  a('campaigns-overview', 'Campaigns Overview', 'Organize campaign drafts and reusable email or SMS content.', [details('Available workspace', 'Campaigns includes campaign lists, a message builder, Email Templates, and SMS Templates.', 'You can prepare content, preview it, and work with saved campaign records.', 'Delivery, scheduling, and audience selection have limitations described in the related articles.')], { notes: [deliveryNote], related: ['creating-campaigns', 'campaign-delivery', 'email-templates'] }),
  a('creating-campaigns', 'Creating a Campaign', 'Prepare a message draft in the campaign builder.', [steps('Open Campaigns and choose Create Campaign.', 'Enter Campaign Name and choose the message type.', 'For email, enter a Subject Line; write the message content or start from a template.', 'Review the preview and choose Save Draft.', 'Return to the campaign list and verify the saved draft. If saving fails, keep a copy of your content and report the error.')], { notes: [deliveryNote, 'Audience choices in the current builder are not a verified end-to-end recipient selection flow.'], related: ['email-campaigns', 'sms-campaigns', 'target-audiences'], keywords: ['create', 'new', 'draft', 'marketing'] }),
  a('email-campaigns', 'Email Campaigns', 'Prepare an email subject and message for a campaign.', [steps('Choose Email in the campaign builder.', 'Enter the campaign name, subject, and body.', 'Review the email preview and save the draft.')], { notes: [deliveryNote, 'Workflow email through a connected Gmail account is a separate feature; it does not make campaign sending operational.'], related: ['email-templates', 'campaign-delivery'] }),
  a('sms-campaigns', 'SMS Campaigns', 'Draft SMS messages and reusable SMS templates.', [details('Current availability', 'SMS content and template screens are available for message preparation.', 'The campaign sending path does not implement production SMS delivery. An Android SMS gateway is not connected to this flow.', 'A preview or sent status does not verify delivery to a mobile phone.')], { related: ['sms-templates', 'campaign-delivery', 'scheduling-campaigns'], keywords: ['text message', 'android', 'gateway', 'delivery'] }),
  a('multi-channel-campaigns', 'Multi-channel Campaigns', 'Understand the limits of combining email and SMS.', [details('Current availability', 'The campaign type model includes Multi-channel.', 'This version does not provide a verified combined email and SMS delivery flow. Do not plan an operational broadcast around this option.', 'Prepare reusable content in the Email Templates and SMS Templates libraries while delivery support is completed.')], { related: ['email-templates', 'sms-templates', 'campaign-delivery'] }),
  a('target-audiences', 'Understanding Campaign Target Audiences', 'Understand what the audience controls currently do.', [details('Current limits', 'The builder offers All Contacts and named audience choices. Its Create Target Audience panel accepts a name and conditions.', 'Audience names created in that panel are held in the current screen state. They are not a reliable saved segmentation workflow.', 'The send path does not reliably connect the selected audience to recipient resolution. Recipient eligibility and production targeting cannot be inferred from the displayed audience name.')], { notes: ['Do not assume that choosing an audience will send only to matching contacts. Operational audience targeting requires further implementation.'], related: ['creating-campaigns', 'campaign-delivery'], keywords: ['recipient', 'segment', 'conditions', 'all contacts'] }),
  a('sms-templates', 'Creating SMS Templates', 'Save a reusable text message in the SMS template library.', [steps('Open Campaigns → SMS Templates and select New SMS Template.', 'Enter Template Name and choose Category: Marketing, Sales, Onboarding, or Support.', 'Write Message Content. Use Insert Variable to append a supported placeholder.', 'Select Save Template, then reopen or refresh the library to verify it saved.'), details('Variables offered by the editor', '{{first_name}}, {{last_name}}, {{company_name}}, {{sender_name}}, and {{sender_email}}.', 'For example: Hi {{first_name}}, thank you for your inquiry.')], { notes: ['Template name and message content are required. Saving a template does not send an SMS; variable insertion does not verify a delivery integration.'], related: ['sms-campaigns', 'email-templates'], keywords: ['create', 'phone', 'placeholder', 'variable', 'text'] }),
  a('email-templates', 'Creating Email Templates', 'Create reusable email text with a subject line.', [steps('Open Campaigns → Email Templates and select New Email Template.', 'Enter Template Name and Category.', 'Enter Subject Line and Message Content.', 'Use Insert Variable for {{first_name}}, {{last_name}}, {{company_name}}, {{sender_name}}, or {{sender_email}}.', 'Select Save Template and verify the saved item in the library. Use Preview to inspect it or Use Template to start campaign content.')], { notes: ['This template editor uses a subject input and a message text area. It is not an advanced visual HTML editor.', 'Do not assume an existing template has been updated when creating a new one; this guide covers the visible creation flow.'], related: ['email-campaigns', 'workflow-actions'], keywords: ['create', 'subject', 'body', 'placeholder', 'variable'] }),
  a('scheduling-campaigns', 'Scheduling Campaigns', 'Understand the scheduling controls and current delivery limitation.', [details('Current availability', 'The builder exposes a scheduling option with date and time fields.', 'The scheduler’s bulk email and SMS senders are not wired to actual transports. Recording a schedule does not establish that delivery will occur.', 'Use campaign drafts for preparation and confirm delivery support with your administrator before relying on any schedule.')], { related: ['campaign-statuses', 'campaign-delivery'], keywords: ['schedule', 'date', 'time', 'send later'] }),
  a('campaign-metrics', 'Campaign Metrics', 'Read campaign counts without confusing them with verified delivery.', [details('What the screen shows', 'Campaign screens use stored sent, opened, and clicked counts to display metrics.', 'Open-rate summaries are calculated from campaigns with sent counts.', 'Because campaign delivery is incomplete, displayed figures, previews, or sample report content are not a verified end-to-end delivery report.')], { related: ['campaign-delivery', 'campaign-statuses'] }),
  a('campaign-statuses', 'Campaign Statuses', 'Read the campaign lifecycle labels.', [details('Status labels', 'Draft identifies saved preparation. Scheduled identifies a planned send time.', 'Active, Paused, and Completed describe campaign state.', 'These states are not delivery receipts. The current send action changes state without a complete message transport.')], { related: ['scheduling-campaigns', 'campaign-metrics'] }),
  a('campaign-delivery', 'Campaign delivery and current limitations', 'Why a sent message or status does not confirm campaign delivery.', [details('Before relying on a campaign', 'Campaign send currently records an active state and a send timestamp without implementing recipient delivery.', 'Scheduled campaign email and SMS transports are placeholders. SMS gateway delivery is not implemented in this path.', 'Audience creation and selection are not connected as a complete saved targeting workflow.', 'Keep operational delivery expectations separate from draft, template, and preview features.')], { related: ['campaign-problems', 'target-audiences'], keywords: ['not sent', 'failed', 'email', 'sms', 'transport'] }),
];
