import { articleFactory, details, steps } from './types';
const c = articleFactory('contacts');
const a = articleFactory('accounts');
export const contactArticles = [
  c('what-is-contact', 'What is a Contact?', 'Contacts store people and customer relationships separately from prospective leads.', [details('Contacts and leads', 'Create a contact directly or create/link one when converting a lead.', 'Link the contact to an Account to identify the organization they belong to. A typed company name is not a substitute for selecting an account.', 'Workflows may call a contact a Client Profile. This refers to the customer contact record.')], { related: ['crm-records', 'creating-contacts'] }),
  c('creating-contacts', 'Creating a Contact', 'Add a person to your customer records.', [steps('Open Contacts and choose Create Contact.', 'Enter First Name and Last Name; both are required.', 'Add Email, Phone, and Company Name. Use a valid email when provided.', 'Review Status and Source, select an Account and Assigned Agent, and add product interests or an address when needed.', 'Select Create Contact and resolve validation messages.')], { notes: ['The PH (+63) phone input accepts the 10-digit mobile part starting with 9. Example: 9123456789 becomes +639123456789.', 'Creating contacts requires contact creation access.'], related: ['contact-account', 'phone-validation'], keywords: ['create', 'new', 'phone'] }),
  c('editing-contacts', 'Editing Contact Information', 'Update a contact’s details without creating a duplicate.', [steps('Open the contact’s side panel from Contacts.', 'Choose Edit in the side panel and change the relevant information. The full detail page’s Edit button is still a placeholder.', 'Select Save Changes and review the updated record.')], { notes: ['Changes require contact editing access. Some relationship information is controlled by linked deals rather than a freely editable status field.'], related: ['contact-details', 'contact-account'] }),
  c('contact-account', 'Linking Contacts to Accounts', 'Associate a person with an existing company record.', [steps('Open the contact’s creation or editing form.', 'Search for and select the company in Account.', 'Save the contact and check its related company information.')], { notes: ['Create the account first if the organization does not exist. Selecting an account creates a relationship; entering Company Name alone does not.'], related: ['creating-accounts', 'editing-contacts'], keywords: ['company', 'link', 'organization'] }),
  c('contact-details', 'Contact Details', 'Review a customer’s information and related records.', [steps('Select a contact in the list.', 'Review contact information and company details in Overview.', 'Review related Deals and Tasks and the activity area.', 'Use the side-panel Edit action to change contact information. Use Archive when available to your role.')], { related: ['editing-contacts', 'linking-tasks', 'deal-relationships'] }),
  c('filtering-contacts', 'Filtering Contacts', 'Find contacts using search and the available list filters.', [steps('Open Contacts and enter a query in its search box.', 'Use Customer Type, Owner, Updated Records, Never Updated, or Contacts with Deals filters to narrow the list.', 'Clear the query and filters if the contact does not appear.')], { notes: ['The contact list searches displayed names, email, and company. Global Search also searches stored contact names and phone numbers. Results are limited to the workspace and your access.'], related: ['global-search', 'missing-records'] }),
  c('sorting-contacts', 'Sorting Contacts', 'Order the contact table using its sortable fields.', [steps('Switch Contacts to table view.', 'Choose the desired sorting direction from a sortable column header.', 'Use pagination to review additional results.')], { related: ['contact-columns', 'filtering-contacts'] }),
  c('contact-columns', 'Managing Contact Columns', 'Personalize the fields displayed in the contact table.', [steps('Open Manage Columns in Contacts.', 'Choose visible columns and their order.', 'Save your preferences, or reset columns to return to the defaults.')], { related: ['sorting-contacts', 'contact-details'] }),
  c('archiving-contacts', 'Archiving Contacts', 'Remove a contact from active lists while retaining its archived record.', [steps('Open the contact’s full detail page.', 'Choose Archive. The list and side panel may label the archive action Delete.', 'Read the confirmation and confirm the action.')], { notes: ['Archiving requires contact archive/delete access. Settings → Archived Data does not provide reliable server-backed recovery for every type; ask your administrator about recovery.'], related: ['archived-data', 'missing-records'] }),
];
export const accountArticles = [
  a('what-is-account', 'What is an Account?', 'Accounts represent organizations or companies associated with your customers.', [details('Use an account to group relationships', 'Store organization details, classification, address, and assigned agent.', 'Select the account on contact and deal forms to link people and sales opportunities.', 'CRM Accounts are company records. Settings → Organization → General shows your LeadCRM workspace identity and status.')], { related: ['creating-accounts', 'crm-records', 'general-settings'] }),
  a('creating-accounts', 'Creating an Account', 'Add a company using the New Account form.', [steps('Open Accounts and choose Create Account.', 'Enter Account Name, which is required and allows up to 255 characters.', 'Add Industry, Size, Website, and Tax ID when known.', 'Set Customer Type and Customer Since if applicable.', 'Enter Street Address, City, and Province, then select an Assigned Agent.', 'Save the account and review any validation messages.')], { notes: ['Website must be a valid URL when supplied. Tax ID is optional; when supplied, enter exactly nine digits without separators.', 'Country is fixed to Philippines in the account form.'], related: ['account-classification', 'account-address', 'validation-errors'], keywords: ['create', 'new', 'tax', 'tin'] }),
  a('editing-accounts', 'Editing an Account', 'Keep company information up to date.', [steps('Open the account’s side panel from Accounts.', 'Choose Edit in the side panel and update the company information. The full detail page’s Edit control is still a placeholder.', 'Select Save Changes and review the result.')], { notes: ['Account editing access is required. Changes to the account do not replace the need to maintain individual contacts.'], related: ['account-address', 'account-classification'] }),
  a('account-contacts', 'Linking Contacts to an Account', 'Connect customer contacts to their company.', [steps('Create the company in Accounts if it does not exist.', 'Open each contact’s Edit form.', 'Choose the company in the Account selector and save.', 'Review linked contacts in the account’s related-record area.')], { related: ['contact-account', 'creating-contacts'] }),
  a('account-deals', 'Linking Deals to an Account', 'Associate a sales opportunity with the company buying from you.', [steps('Create or edit the deal.', 'Choose the company in its Account relationship field.', 'Save the deal and review the linked account.')], { notes: ['An account and a contact serve different purposes. Select the relevant contact separately when you want a person linked to the deal.'], related: ['deal-relationships', 'creating-deals'] }),
  a('account-classification', 'Customer Classification', 'Describe the account’s relationship with your business.', [details('Customer fields', 'Customer Type offers Prospect, Active Customer, Inactive Customer, and Former Customer.', 'Customer Since records the start of the customer relationship.', 'Size options are 1–10, 11–50, 51–200, and 200+.'), steps('Open the account’s Edit form.', 'Review Customer Classification and update the applicable values.', 'Save Changes.')], { related: ['editing-accounts', 'what-is-account'] }),
  a('account-address', 'Account Address', 'Maintain a Philippine company address.', [steps('Create or edit an account.', 'Enter Street Address, City, and Province.', 'Review the read-only Country value, Philippines, and save.')], { notes: ['Keep address details in the address fields rather than adding them to Account Name.'], related: ['creating-accounts', 'editing-accounts'] }),
  a('filtering-accounts', 'Filtering Accounts', 'Find company records using the account list controls.', [steps('Open Accounts and search by account name, industry, or city.', 'Use the available filters to narrow the list.', 'Clear filters and check your access if the company is missing.')], { related: ['global-search', 'missing-records'] }),
  a('archiving-accounts', 'Archiving Accounts', 'Remove a company from active account lists.', [steps('Open the account’s full detail page.', 'Choose Archive and read the confirmation. The table and side panel use Delete for the account archive action.', 'Confirm the archive when the company should leave the active list.')], { notes: ['Do not treat archiving an account as a bulk archive of all related records. Review linked contacts and deals separately.', 'Ask an administrator about recovery; the Settings recovery list is not a complete live recovery tool.'], related: ['archived-data', 'account-contacts', 'account-deals'] }),
];
