import { articleFactory, details, steps } from './types';
const a = articleFactory('dashboard');
export const dashboardArticles = [
  a('dashboard-overview', 'Understanding the Dashboard', 'Review sales totals, follow-up work, and pipeline distribution.', [steps('Open Dashboard and check the workspace.', 'Review the cards available to your role.', 'Use Action Center and the charts to decide which records need attention.', 'Reload the page if you need to request updated workspace data.')], { notes: ['Client Admin and staff views differ. Metrics use the data available to the dashboard and are not a separate financial accounting report.'], related: ['revenue-metrics', 'action-center', 'sync-metrics'] }),
  a('revenue-metrics', 'Revenue Metrics', 'Total Revenue sums values of non-archived deals in won stages.', [details('Reading revenue', 'For example, won deals of ₱25,000 and ₱40,000 contribute ₱65,000.', 'Stage won/lost settings determine which deals count. Merely naming a stage “Won” is not a substitute for its won flag.', 'Revenue here is deal value, not collected payments or invoiced revenue.')], { related: ['won-lost', 'forecasted-revenue'] }),
  a('forecasted-revenue', 'Forecasted Revenue', 'Forecasted revenue weights open deal values by their stage probabilities.', [details('Calculation', 'Each open deal contributes its value multiplied by its stage probability divided by 100.', 'A ₱50,000 deal in a 40% stage contributes ₱20,000.', 'When a stage probability is missing, the dashboard uses 10%. Won, lost, and archived deals are excluded from this open-deal forecast.')], { related: ['pipeline-stages', 'revenue-metrics'], keywords: ['forecast', 'probability', 'peso'] }),
  a('active-deals', 'Active Deals', 'Count opportunities that have not reached won or lost stages.', [details('What is included', 'Active Deals includes non-archived deals outside won and lost stages.', 'My Active Deals narrows that set to deals assigned to the signed-in user.', 'A filter change can explain differences between lists and dashboard counts.')], { related: ['pipeline-stages', 'missing-records'] }),
  a('total-leads', 'Total Leads', 'Read the lead total for the workspace.', [details('Reading the card', 'Total Leads uses the lead count request rather than the number of contacts shown on a loaded page.', 'It is not the number of Accounts, Contacts, or Deals.', 'Refresh after creating or archiving records if the display has not updated.')], { related: ['sync-metrics', 'what-is-lead'] }),
  a('win-rate', 'Win Rate', 'Understand the dashboard’s won-deal percentage.', [details('Calculation', 'Win Rate is the number of non-archived won deals divided by all non-archived deals, rounded to a whole percentage.', 'Open deals are included in the denominator. It is not won divided only by won plus lost.', 'When there are no non-archived deals, the card shows 0%.')], { related: ['won-lost', 'active-deals'] }),
  a('average-velocity', 'Average Velocity', 'Review the average days to reach a won stage.', [details('Calculation', 'The dashboard uses won deals that have a last stage-change date.', 'For each included deal, it measures rounded days from creation to that date, with a minimum of one day, then averages the values.', 'A dash can indicate that no qualifying won deals are available.')], { related: ['won-lost', 'dashboard-overview'] }),
  a('revenue-trend', 'Revenue Trend', 'View won-deal value over the recent six months.', [details('Reading the chart', 'Monthly totals use the last stage-change date of won deals.', 'The chart displays deal value in Philippine pesos. It does not represent payment collection dates.', 'Revenue & Deals compares the monthly value and number of won deals.')], { related: ['revenue-metrics', 'dashboard-export'] }),
  a('action-center', 'Action Center', 'Review follow-up items surfaced on the dashboard.', [steps('Open Dashboard and find Action Center.', 'Review overdue or pending work displayed for your user.', 'Open the relevant module to update the task or record.')], { notes: ['Some personal lead indicators depend on loaded workspace data and may be incomplete in live mode. Check Leads and Tasks directly before concluding there is no work.'], related: ['daily-workflow', 'completing-tasks'] }),
  a('sales-leaderboard', 'Sales Leaderboard', 'Compare users by won-deal value.', [details('Reading the leaderboard', 'Users are ranked by the summed value of their non-archived won deals.', 'The dashboard shows the top five, along with won and active deal counts.', 'The values depend on deal assignment and the workspace.')], { related: ['revenue-metrics', 'active-deals'] }),
  a('pipeline-distribution', 'Pipeline Distribution', 'See how deals are distributed across stages.', [details('Reading the chart', 'The chart groups non-archived deals by stage and excludes lost stages.', 'Won stages may still appear; this chart is not limited to open opportunities.', 'Use the pipeline board for the underlying deals and stage details.')], { related: ['pipeline-view', 'pipeline-stages'] }),
  a('sync-metrics', 'Sync Metrics: current limitation', 'The current Sync Metrics control only displays a confirmation message.', [details('Refreshing data', 'Sync Metrics does not currently request fresh metrics. Its success toast is not confirmation of a data refresh.', 'Reload the page to request workspace data and check the underlying module if a number remains unexpected.', 'Some counts are cached, so a reload may not immediately change every total.')], { notes: ['No external accounting or calendar synchronization is provided by this control.'], related: ['dashboard-overview', 'missing-records'] }),
  a('dashboard-export', 'Export Dashboard CSV', 'Download the dashboard’s available summary data.', [steps('Open Dashboard in the workspace.', 'Check the displayed values against the underlying modules if needed.', 'Select Export CSV to download the report.')], { notes: ['The export contains dashboard metrics and available chart/leaderboard data for your view. It is not an export of every CRM record.'], related: ['dashboard-overview', 'revenue-trend'], keywords: ['export', 'download', 'csv'] }),
];
