import { articleFactory, details, steps } from './types';
const a = articleFactory('dashboard');
export const dashboardArticles = [
  a('dashboard-overview', 'Understanding the Dashboard', 'Review sales totals, follow-up work, and pipeline distribution.', [steps('Open Dashboard and check the workspace.', 'Review the cards available to your role.', 'Use Action Center and the charts to decide which records need attention.', 'Dashboard updates automatically. Use Sync Metrics to request a fresh report when needed.')], { notes: ['Client Admin and users granted Dashboard View see permitted organization-wide analytics. Action Center retains its own authorized action scope. Deal revenue is not collected payments.'], related: ['revenue-metrics', 'action-center', 'sync-metrics'] }),
  a('revenue-metrics', 'Revenue Metrics', 'Total Revenue sums eligible Closed Won deal values across the organization for the selected reporting period.', [details('Reading revenue', 'For example, won deals of ₱25,000 and ₱40,000 contribute ₱65,000.', 'The official Closed Won stage and a valid closing timestamp determine inclusion. Archived, deleted and other-currency deals are excluded; incomplete amounts remain unavailable.', 'Revenue here is deal value, not collected payments or invoiced revenue.')], { related: ['won-lost', 'forecasted-revenue'] }),
  a('forecasted-revenue', 'Forecasted Revenue', 'Forecasted revenue weights open deal values by their stage probabilities.', [details('Calculation', 'Each open deal contributes its value multiplied by its stage probability divided by 100.', 'A ₱50,000 deal in a 40% stage contributes ₱20,000.', 'Missing probability makes the affected forecast unavailable. Configured zero remains zero. Won, lost, archived and deleted deals are excluded.')], { related: ['pipeline-stages', 'revenue-metrics'], keywords: ['forecast', 'probability', 'peso'] }),
  a('active-deals', 'Active Deals', 'Count opportunities that have not reached won or lost stages.', [details('What is included', 'Active Deals includes all eligible organization deals currently in Lead, Contacted or Qualified.', 'Dashboard analytics remain organization-wide for authorized reporting users. Deal-list filters may show a smaller set.', 'A filter change can explain differences between lists and dashboard counts.')], { related: ['pipeline-stages', 'missing-records'] }),
  a('total-leads', 'Total Leads', 'Read the lead total for the workspace.', [details('Reading the card', 'Total Leads uses the lead count request rather than the number of contacts shown on a loaded page.', 'It is not the number of Accounts, Contacts, or Deals.', 'The card counts current unconverted, unarchived and undeleted organization Leads and updates automatically.')], { related: ['sync-metrics', 'what-is-lead'] }),
  a('win-rate', 'Win Rate', 'Understand the dashboard’s won-deal percentage.', [details('Calculation', 'Win Rate is eligible period Closed Won divided by Closed Won plus Closed Lost, rounded to one decimal place.', 'Open deals are excluded from the denominator. Won/Lost counts use valid closing dates in the global reporting period.', 'When there are no eligible resolved outcomes, the card shows Unavailable.')], { related: ['won-lost', 'active-deals'] }),
  a('average-velocity', 'Average Velocity', 'Review the average days to reach a won stage.', [details('Calculation', 'The dashboard uses eligible Closed Won deals with valid closing timestamps in the selected reporting period.', 'It averages fractional days from creation to closure, rounded to one decimal place. Same-day deals can close in less than one day.', 'Unavailable indicates that no qualifying won deals can establish a closing duration.')], { related: ['won-lost', 'dashboard-overview'] }),
  a('revenue-trend', 'Revenue Trend', 'Group organization Closed Won revenue by calendar Week, Month or Year within the global reporting period.', [details('Reading the chart', 'The filter beside Won Deals changes calendar grouping using closing timestamps in Asia/Manila. The global date range remains unchanged.', 'The chart displays deal value in Philippine pesos. It does not represent payment collection dates.', 'Bucket revenue reconciles with Total Revenue; Won Deals uses the same selected reporting period.')], { related: ['revenue-metrics', 'dashboard-export'] }),
  a('action-center', 'Action Center', 'Review follow-up items surfaced on the dashboard.', [steps('Open Dashboard and find Action Center.', 'Review overdue or pending work displayed for your user.', 'Open the relevant module to update the task or record.')], { notes: ['Some personal lead indicators depend on loaded workspace data and may be incomplete in live mode. Check Leads and Tasks directly before concluding there is no work.'], related: ['daily-workflow', 'completing-tasks'] }),
  a('sales-leaderboard', 'Sales Leaderboard', 'Compare users by won-deal value.', [details('Reading the leaderboard', 'Eligible organization agents are ranked by period revenue credited at their first Won closure.', 'The dashboard shows the top five with won counts and credited revenue.', 'Later reassignment or deactivation does not rewrite captured credit. Unknown historical attribution can make leaderboard revenue differ from total revenue.')], { related: ['revenue-metrics', 'active-deals'] }),
  a('pipeline-distribution', 'Pipeline Distribution', 'See how deals are distributed across stages.', [details('Reading the chart', 'The chart groups eligible organization open Deals in Lead, Contacted and Qualified.', 'Won and Lost are excluded. Colors match saved Stage Colors in Deals → Manage pipeline stages.', 'Use the pipeline board for the underlying deals and stage details.')], { related: ['pipeline-view', 'pipeline-stages'] }),
  a('sync-metrics', 'Sync Metrics', 'Request a fresh authorized Dashboard report.', [details('Refreshing data', 'Sync Metrics fetches authoritative metrics and charts. A success message follows a successful report request.', 'Normal cross-user updates are automatic. Use Sync Metrics as a fallback and check the selected reporting dates when reconciling totals.', 'Errors remain visible and can be retried; missing reporting evidence is not replaced with invented values.')], { notes: ['No external accounting or calendar synchronization is provided by this control.'], related: ['dashboard-overview', 'missing-records'] }),
  a('dashboard-export', 'Export Dashboard CSV', 'Download the dashboard’s available summary data.', [steps('Open Dashboard in the workspace.', 'Check the displayed values against the underlying modules if needed.', 'Select Export CSV to download the report.')], { notes: ['The export enforces the same organization permissions, chart filters and historical observation cutoff, with diagnostic warnings. It is not an export of every CRM record.'], related: ['dashboard-overview', 'revenue-trend'], keywords: ['export', 'download', 'csv'] }),
];
