import { articleFactory, details, steps } from './types';
const d = articleFactory('deals');
const t = articleFactory('tasks');
export const dealArticles = [
  d('what-is-deal', 'What is a Deal?', 'A deal represents a sales opportunity moving through a configured pipeline.', [details('What a deal contains', 'A title, pipeline, and stage identify the opportunity and its progress.', 'Value, priority, expected close date, and assigned user help organize the work.', 'Account, contact, and lead links connect the opportunity to CRM records.')], { related: ['creating-deals', 'pipeline-stages'] }),
  d('creating-deals', 'Creating a Deal', 'Record a qualified sales opportunity.', [steps('Open Deals and choose the add/create deal control.', 'Choose a Stage in the fixed Sales Pipeline, then enter a Title. These are required.', 'Select one or more Product Interests. Value is calculated from their configured product values. Choose Low, Medium, or High priority and an Expected Close Date if needed.', 'Select the Account, Contacts, Leads, and Assigned User as applicable.', 'Review the details and save.')], { notes: ['Deal values use Philippine pesos (PHP). The form does not offer currency selection.', 'Creating deals requires deal creation access.'], related: ['pipeline-stages', 'deal-relationships', 'deal-priority'], keywords: ['create', 'new', 'peso', 'value', 'pipeline'] }),
  d('pipeline-stages', 'Understanding Pipeline Stages', 'Stages describe progress within the selected sales pipeline.', [details('How stages work', 'The pipeline selector determines which stages and deals you see. Use your workspace’s actual stage names; pipelines can differ.', 'A stage can be marked won or lost. These stage settings determine the deal’s outcome and dashboard calculations.', 'Open stages can carry a probability used in forecasted revenue. Priority is separate from stage and probability.')], { related: ['moving-deals', 'won-lost', 'forecasted-revenue'], keywords: ['pipeline', 'stage', 'sales'] }),
  d('moving-deals', 'Moving a Deal Between Stages', 'Update an opportunity as the sale progresses.', [steps('Open Deals and select the correct pipeline.', 'In Pipeline view, drag the deal to the destination stage, or use the stage control in its details.', 'If moving to a won or lost stage, complete the requested confirmation and information.', 'Check the deal’s new stage after saving.')], { notes: ['Stage changes require deal editing access. A lost transition requires a reason.'], related: ['pipeline-view', 'won-lost', 'deal-details'] }),
  d('deal-priority', 'Deal Priority', 'Use Low, Medium, or High to indicate attention needed.', [steps('Create or edit the deal.', 'Select Priority.', 'Save your change and use priority filters when reviewing the pipeline.')], { notes: ['Priority does not move a deal or change its forecast probability.'], related: ['creating-deals', 'pipeline-stages'] }),
  d('deal-close-date', 'Expected Close Date', 'Record when you expect an opportunity to close.', [steps('Open the deal’s Edit form.', 'Choose an Expected Close Date.', 'Save Changes and revise the date when your estimate changes.')], { notes: ['An expected date is a planning field. It does not automatically move the deal to a won stage.'], related: ['won-lost', 'creating-deals'] }),
  d('deal-relationships', 'Linking Accounts and Contacts to Deals', 'Connect the opportunity to its company and people.', [steps('Create or edit a deal and open Relationships.', 'Select an Account when the opportunity belongs to a company.', 'Choose the relevant Contacts and Leads using their selectors.', 'Save and check the relationships in the deal details.')], { notes: ['Only link records from the current workspace. A company name in free text does not create an account link.'], related: ['account-deals', 'contact-account', 'converting-leads'] }),
  d('won-lost', 'Marking Deals Won or Lost', 'Record the outcome using a stage configured as won or lost.', [steps('Open the correct pipeline and deal.', 'Move to the appropriate won or lost stage.', 'Complete the outcome confirmation. For a lost deal, enter the loss reason.', 'Review the saved outcome and associated customer information.')], { notes: ['A stage’s won/lost setting matters, not just its display name. Outcome transitions may require additional information or reject invalid moves.'], related: ['moving-deals', 'revenue-metrics'] }),
  d('deal-details', 'Deal Details', 'Review the opportunity, related customers, and follow-up work.', [steps('Select the deal title to open its details.', 'Review Overview and related records, then check activities and tasks.', 'Use the available edit and stage actions to keep the opportunity current.')], { related: ['deal-relationships', 'linking-tasks', 'moving-deals'] }),
  d('pipeline-view', 'Pipeline View', 'Review sales opportunities grouped by stage.', [steps('Open Deals and select a pipeline.', 'Choose Pipeline/board view to see stage columns.', 'Use search and status, stage, staff, or priority filters to focus the board.', 'Load more deals in a stage when available, or open a card for details.')], { related: ['moving-deals', 'deal-table'] }),
  d('deal-table', 'Table View', 'Review deals as rows rather than stage cards.', [steps('Open Deals and switch to Table view.', 'Use the available search, filters, and sortable headings.', 'Select a deal to open its details. Switch back to the board to review stage distribution.')], { related: ['pipeline-view', 'deal-details'] }),
];
export const taskArticles = [
  t('creating-tasks', 'Creating Tasks', 'Record follow-up work for yourself or a teammate.', [steps('Open Tasks and select New Task, or use the add control in a board column.', 'Enter the required Task Title and a Description if useful.', 'Choose Priority, Assignee, Due Date, and Status.', 'Save the task and verify it appears in the appropriate column.')], { related: ['assigning-tasks', 'task-due-dates', 'linking-tasks'], keywords: ['create', 'new', 'follow up'] }),
  t('assigning-tasks', 'Assigning Tasks', 'Give a follow-up task a responsible user.', [steps('Create a task or open its Edit form.', 'Choose a workspace user in Assignee.', 'Save and use the assignee filter to review that person’s work.')], { related: ['filtering-tasks', 'creating-tasks'] }),
  t('task-priority', 'Task Priority', 'Distinguish urgent work with High, Medium, and Low priorities.', [steps('Open the task’s creation or editing form.', 'Select a Priority and save.', 'Use Priority Levels in the task filters to focus your review.')], { related: ['task-due-dates', 'filtering-tasks'] }),
  t('task-due-dates', 'Due Dates', 'Set a date for follow-up work and review overdue tasks.', [steps('Create or edit a task and choose its Due Date.', 'Save and review its due-date badge on the board or list.', 'Complete finished work so it is no longer shown as overdue.')], { notes: ['An overdue task is past its due date and is neither completed nor cancelled. A due date does not imply external calendar synchronization.'], related: ['completing-tasks', 'daily-workflow'] }),
  t('linking-tasks', 'Linking Tasks to CRM Records', 'Create follow-up work in the context of a lead, contact, or deal.', [steps('Select the CRM record in its module list to open the side panel, then open its Tasks area.', 'Use the side panel’s add task action. The full detail page’s related list may only show existing tasks.', 'Enter the task information and save.', 'Review the task in the record’s related work.')], { notes: ['The standalone Tasks form has no general record-link picker. Start from the CRM record when you need a linked task. Supported workflow Create task actions also create linked follow-ups.'], related: ['lead-details', 'deal-details', 'workflow-actions'] }),
  t('completing-tasks', 'Completing Tasks', 'Mark finished work as completed or reopen it when needed.', [steps('Open Tasks and find the task.', 'Choose Mark done from its options, or edit its status to Completed.', 'Use Reopen if the work needs attention again.')], { notes: ['The board shows To Do, In Progress, Blocked, and Completed columns. Moving a card between columns changes its status.'], related: ['filtering-tasks', 'task-due-dates'] }),
  t('filtering-tasks', 'Filtering Tasks', 'Focus on specific assignees, priorities, or statuses.', [steps('Open Tasks and search by title or description.', 'Select the desired assignee, Priority Levels, and status filters.', 'Switch between Board, List, and Workload views as needed.', 'Clear the filters to broaden the results.')], { related: ['assigning-tasks', 'completing-tasks'] }),
];
