import { articleFactory, details, steps } from './types';
const a = articleFactory('getting-started');
export const gettingStartedArticles = [
  a('welcome', 'Getting started with LeadCRM', 'Keep prospects, customer contacts, companies, deals, follow-up tasks, and team access together.', [
    details('Welcome to LeadCRM', 'Use Leads for prospective customers and Contacts for ongoing customer relationships. Accounts represent the companies they belong to.', 'Use Deals to track sales opportunities through a pipeline. Tasks record the next follow-up. Campaigns hold message plans and templates; Workflows automate supported record events.'),
    steps('Open Leads, Contacts, Accounts, or Deals from the sidebar.', 'Create a record or open an existing one to review its details.', 'Add a follow-up task and keep ownership and deal stages current.'),
  ], { related: ['interface', 'crm-records', 'first-setup'], keywords: ['welcome', 'start', 'new user'] }),
  a('interface', 'Understanding the LeadCRM interface', 'Find the sidebar, workspace, search, and account controls.', [details('Your workspace', 'The left sidebar opens Dashboard, Leads, Contacts, Accounts, Deals, Tasks, Campaigns, Workflows, and Settings when your role has access.', 'The main workspace shows the selected module. The top-bar breadcrumb identifies your current area.', 'All Modules scopes record search.', 'The mail icon opens Messages with Gmail connection features. The bell opens notifications. Your avatar opens account settings, Appearance, Help Center, and Log out.')], { related: ['sidebar', 'global-search'] }),
  a('sidebar', 'Navigating with the sidebar', 'Move between the modules available to your role.', [steps('Select a module name in the sidebar to open its workspace.', 'On a small screen, use Open sidebar in the top bar, then select the module.', 'Open Settings for profile, organization, team, and configuration pages.')], { notes: ['Missing modules can reflect your assigned permissions. Ask your workspace administrator to check your access.'], related: ['module-access', 'interface'] }),
  a('global-search', 'Using Global Search', 'Search Leads, Contacts, Accounts, and Deals from the top bar.', [
    steps('Choose All Modules or a specific module in the search selector.', 'Enter at least three characters. On desktop, press / outside a form field to focus search; on mobile, open the search icon.', 'Select a result to open its record. Refine the query when you need a more specific match.'),
    details('What is searched', 'Leads: first name, last name, email, and company name.', 'Contacts: first name, last name, email, company, and phone.', 'Accounts: account name, industry, and city.', 'Deals: title and company name among the deals already loaded in the workspace. A # query matches deal priority or lead source; it is not a universal tag index.'),
  ], { notes: ['The dropdown shows up to four results per module. Tasks and Campaigns are not part of this search. Use the module’s own search if a record is not in the dropdown.'], related: ['missing-records', 'searching-leads'], keywords: ['all modules', 'search records', 'omnibox', 'find'] }),
  a('crm-records', 'Understanding Leads, Contacts, Accounts & Deals', 'Choose the record type that matches what you are tracking.', [
    details('Record relationships', 'Lead: a prospective customer being qualified.', 'Contact: a person or customer relationship, which can be created directly or linked during lead conversion.', 'Account: an organization or company linked to people and deals.', 'Deal: a sales opportunity with a pipeline, stage, value, and owner.'),
    details('From prospect to sale', 'Lead conversion lets you create or select an account and contact, and optionally create or link a deal. The lead is marked Converted.', 'A deal progresses through your configured pipeline to a stage marked won or lost. Changing a lead’s status alone is not the conversion process.'),
  ], { related: ['converting-leads', 'creating-deals', 'what-is-account'] }),
  a('first-setup', 'Recommended first setup', 'Prepare your profile and workspace before entering operational records.', [steps('Open Settings → Profile Settings and review your details.', 'Choose your preferred Appearance.', 'If you administer the workspace, review General, Team Management, and Roles & Permissions.', 'Create an account and lead, then record the next follow-up task.')], { related: ['profile-settings', 'general-settings', 'creating-leads'] }),
  a('daily-workflow', 'A basic daily workflow', 'Review priorities, update records, and leave a clear next step.', [steps('Review Dashboard and Tasks.', 'Open the lead, contact, or deal you are following up.', 'Update editable details and assignment as needed.', 'Complete finished tasks and create the next follow-up.', 'Move deals to the stage that reflects their actual progress.')], { related: ['dashboard-overview', 'completing-tasks', 'moving-deals'] }),
];
