import { articleFactory, details, steps } from './types';
const a = articleFactory('leads');
export const leadArticles = [
  a('what-is-lead', 'What is a Lead?', 'A lead records a prospective customer before qualification and conversion.', [details('When to use Leads', 'Capture the person’s name, contact information, company, source, and product interest.', 'Assign an agent and update the status as qualification progresses.', 'Use conversion when you want to create or link the account, contact, and optional deal.')], { related: ['creating-leads', 'converting-leads'] }),
  a('creating-leads', 'Creating a Lead', 'Add a prospective customer using the New Lead side panel.', [steps('Open Leads and select Create Lead.', 'Enter First Name and Last Name. Both are required; each allows up to 100 characters.', 'Add Email, Phone, and Company Name when known. A supplied email must be valid.', 'Choose Status and Product Interest, then select an Account if applicable.', 'Set Lead Source, Assigned Agent, and Address as needed.', 'Select Create Lead and resolve any highlighted validation errors.')], { notes: ['For PH (+63), enter the 10-digit mobile part beginning with 9, for example 9123456789. It is stored as +639123456789.', 'Creating leads requires contact creation access.'], related: ['lead-status', 'assigning-leads', 'phone-validation'], keywords: ['create', 'new', 'phone', 'first name', 'email'] }),
  a('editing-leads', 'Editing a Lead', 'Keep prospect information current.', [steps('Open Leads and select the record to open its side panel, or open its full record page.', 'Select the Details tab and choose an editable field.', 'Update the field and select Save, or select Cancel to discard the edit.', 'Check the saved record before leaving.')], { notes: ['Editing requires contact editing access. Read-only metadata, such as creation dates, is not an editable form field.'], related: ['lead-details', 'lead-status'] }),
  a('lead-status', 'Understanding Lead Status', 'Use status to describe the current state of qualification.', [details('Available choices', 'Lead status choices are Hot, Warm, Cold, Closed, and Cancelled in forms and record views.', 'Older unsupported status values display safely as Warm in the record panel until you update the record.', 'Converting a lead changes its status to Closed and links or creates its contact and account.')], { related: ['editing-leads', 'converting-leads'] }),
  a('assigning-leads', 'Assigning Leads', 'Set the agent responsible for a prospect.', [steps('Create a lead or open its Edit form.', 'Find Assigned Agent in the additional information fields.', 'Select a workspace user and save.'), details('Finding your work', 'Use the My Leads view or owner filters to focus on assigned prospects.')], { related: ['searching-leads', 'creating-tasks'] }),
  a('searching-leads', 'Searching and Filtering Leads', 'Narrow the list by query, status, source, and owner.', [steps('Open Leads and enter a name, email, or company in its search box.', 'Choose a view and use the filter rail to select statuses, lead sources, or owners.', 'Clear filters and the query to return to the broader list.')], { notes: ['Some filter counts and touched/untouched checks reflect the loaded page. Check your access and archived state when a lead is missing.'], related: ['sorting-leads', 'missing-records'], keywords: ['find', 'filter', 'search'] }),
  a('sorting-leads', 'Sorting Leads', 'Change the order of records in the lead table.', [steps('Open the table view in Leads.', 'Use a sortable column header or its sorting menu to choose ascending or descending order.', 'Use the page controls to move through the sorted results.')], { related: ['lead-columns', 'searching-leads'] }),
  a('lead-columns', 'Managing Lead Columns', 'Choose which lead fields appear in the table.', [steps('Open Manage Columns from the lead table controls.', 'Select the columns you need and adjust their order.', 'Save the column configuration. Use Reset Columns to return to defaults.')], { notes: ['Column preferences change the table display, not the values stored on records.'], related: ['sorting-leads', 'lead-details'] }),
  a('importing-leads', 'Importing Leads', 'Use the lead import flow to map and validate a CSV file.', [steps('Open Leads → Import and use the downloadable template as your starting point.', 'Upload the CSV and map its columns to LeadCRM fields.', 'Map First Name, Last Name, Email, Phone Number, Company Name, and Full Address. These are required by the import configuration.', 'Map optional Website, Lead Source, Description, and Status when present.', 'Review validation and duplicate results, correct errors, and complete the import.', 'Review the import details for imported, skipped, or failed rows.')], { notes: ['Import requirements are stricter than the manual New Lead form. Duplicate checking uses email; review matches before continuing.'], related: ['creating-leads', 'validation-errors'], keywords: ['csv', 'upload', 'bulk', 'mapping'] }),
  a('archiving-leads', 'Archiving Leads', 'Remove a prospect from the active working list.', [steps('Open the lead’s full detail page.', 'Select Archive and review the confirmation. The table and side panel use the label Delete for the lead archive action.', 'Confirm only when you want the record removed from active work.')], { notes: ['Archive is not permanent deletion. The Settings recovery screen is not a complete live lead recovery tool; ask an administrator if you need a record restored.'], related: ['archived-data', 'missing-records'] }),
  a('converting-leads', 'Converting a Lead', 'Create or link customer records after qualification.', [steps('Open a lead and choose Convert to contact from its record actions.', 'Review the lead information.', 'Create a new Account or select an existing one.', 'Create a Contact from the lead data or link an existing contact.', 'Optionally enable Create or link a deal. Supply a title and pipeline for a new deal, or select an existing deal.', 'Review the confirmation and complete conversion.')], { notes: ['Conversion marks the source lead Closed and records its links. A lead already converted cannot be converted again.', 'Check the selected existing records carefully to avoid linking the wrong customer.'], related: ['crm-records', 'creating-deals', 'lead-status'], keywords: ['convert', 'qualification', 'contact', 'account'] }),
  a('lead-details', 'Lead Profile / Details', 'Review prospect information and related work in one place.', [steps('Select a lead from the list to open its side panel; use the full-record control for its detail page.', 'Use Activity to review emails, status changes, and follow-up tasks.', 'Use Details to view or edit lead fields and linked records.', 'Use Files to upload and review attachments.')], { related: ['editing-leads', 'linking-tasks', 'converting-leads'] }),
];
