import { articleFactory, details, steps } from './types';
const a = articleFactory('settings');
const s = articleFactory('security');
export const settingsArticles = [
  a('profile-settings', 'Profile Settings', 'Edit the personal information visible to your teammates.', [steps('Open Settings → Profile Settings.', 'Select Edit in Personal Information.', 'Update First Name, Last Name, Phone Number, and Job Title as needed. Groups are displayed from your administrator-managed memberships.', 'Select Save Changes, or Cancel to discard unsaved edits.'), details('Profile photo', 'Select a profile image, adjust the crop, and choose Apply Picture.', 'The image is uploaded separately from the personal-information form. Wait for the successful upload result.')], { notes: ['Email Address is read-only. First Name and Last Name are required.', 'Photo persistence requires configured profile-image storage. If upload fails, the image has not been saved.', 'The profile phone field is a text field; the dedicated PH (+63) input rule applies to lead/contact forms. Profile Settings has no timezone field.'], related: ['appearance', 'readonly-settings', 'phone-validation'], keywords: ['photo', 'avatar', 'phone', 'name', 'email'] }),
  a('appearance', 'Changing LeadCRM Appearance', 'Choose the theme and accent color used by the CRM.', [steps('Open Appearance from your avatar menu or Settings.', 'Choose Classic, Light, Dark, or System.', 'Select an Accent Color if desired.', 'Select Apply Changes to retain your appearance preferences.')], { notes: ['Classic combines a dark sidebar with a light workspace. System follows your operating system’s color preference.', 'The Help Center uses the same theme and accent tokens as the rest of LeadCRM.'], related: ['interface', 'profile-settings'], keywords: ['theme', 'dark mode', 'light mode', 'color'] }),
  a('general-settings', 'General Organization Settings', 'Maintain the workspace’s organization details.', [steps('Open Settings → General under Organization.', 'Select Edit. The fields are read-only initially.', 'Update Organization Name, Industry, Email, Phone, Domain, and Office Address as needed.', 'Select Save Changes, or Cancel to discard unsaved changes.')], { notes: ['Editing requires settings editing access. Organization Name cannot be blank, and a supplied email must be valid.', 'Domain is descriptive organization information; it does not configure team sign-in domains.', 'System Information below Organization Details shows your full Account ID with a Copy button and the current system-managed Account Status. These values stay read-only while editing.', 'Viewing requires Organization Settings view permission. Legacy Account Details links open General.', 'General does not offer currency or timezone settings.'], related: ['readonly-settings', 'what-is-account'], keywords: ['organization', 'company', 'address', 'domain'] }),
  a('custom-fields', 'Custom Fields availability', 'Custom field configuration is currently marked coming soon.', [details('Current availability', 'Settings → Custom Fields displays “Custom fields configuration coming soon.”', 'You cannot create, edit, or delete custom field definitions from that screen in this version.', 'Use the existing record fields. Manage Columns changes the table display and does not create new record fields.')], { related: ['lead-columns', 'contact-columns'], keywords: ['custom fields', 'coming soon', 'configuration'] }),
  a('archived-data', 'Managing Archived Data', 'Understand archiving and the limits of the Settings recovery screen.', [details('Archive versus delete', 'Archiving removes a record from normal active lists while retaining an archived record. It is different from permanent deletion.', 'Settings → Archived Data displays type filters for Contact, Organization, Deal, Pipeline, User, Role, Workflow, Campaign, and Template. Organization is the legacy label used for account recovery.', 'The current Settings Restore controls update local workspace state and are not wired to persistent server recovery for these types. A success toast there is not proof of a live restore.', 'Leads are not a dedicated recovery type in this screen. Archived roles cannot be restored. No permanent-delete procedure is provided here.'), steps('Check the workspace and the original module first.', 'Review available archived records in Settings if you have access.', 'Ask your administrator to arrange recovery of a live record and verify it by reloading the original module.')], { related: ['missing-records', 'archiving-leads', 'role-restrictions'], keywords: ['restore', 'recover', 'archive', 'delete'] }),
  a('forms', 'Creating a Form', 'Create and edit a form definition in Settings.', [steps('Open Settings → Forms and choose the new-form control.', 'Enter a form name and create the draft.', 'Use the field palette to add fields to the canvas.', 'Configure field labels and form design. The builder sends changes as you edit; reopen the form to verify that they persisted.')], { notes: ['The builder has no separate Save button, and some editing errors are not surfaced. Verify changes by reopening the form. Public sharing and CRM submission processing are not established by the editor alone.'], related: ['form-fields', 'form-publishing'], keywords: ['create', 'form', 'builder'] }),
  a('form-fields', 'Form Fields', 'Configure the fields shown in the form builder.', [details('Field palette', 'Layout: Heading, Paragraph, and Divider.', 'CRM-labelled fields: Contact Name, Contact Phone, Contact Email, Company Website, and Company Name.', 'Regular fields: Single Line, Multi Line, Email, Phone, Number, Date, Checkbox, Radio, Dropdown, URL, Rating, and File Upload.'), steps('Open the draft form.', 'Click a palette item or drag it onto the canvas.', 'Select the field to configure it. Changes are sent as you edit; reopen the form to verify persistence.')], { notes: ['A field’s presence in the builder does not establish a public upload service or automatic mapping of submissions into CRM records.'], related: ['forms', 'form-publishing'] }),
  a('form-publishing', 'Publishing and Sharing Forms: current limits', 'Understand what Publish and the generated share controls establish.', [details('Current availability', 'Publish updates a form definition’s published status.', 'The sharing controls generate a forms.leadcrm.app link and embed snippet.', 'This repository does not include the corresponding public form renderer, submission intake, or automatic CRM mapping flow. A generated link is not verification that a public form is usable.')], { notes: ['Do not rely on this version for collecting operational submissions until the public form service and submission handling have been verified.'], related: ['forms', 'form-fields'], keywords: ['publish', 'share', 'embed', 'submission'] }),
];
export const securityArticles = [
  s('account-security', 'Password', 'Manage account security in Profile Settings.', [steps('Open Settings → Profile Settings → Security.', 'Change Password opens a dialog for a strong new password and matching confirmation.'), details('Managing passwords', 'Password changes preserve this session and revoke your other sessions.', 'Use Forgot password on the login page to request a password reset link.')], { related: ['profile-settings'], keywords: ['password', 'security', 'reset'] }),
  s('role-based-access', 'Role-Based Access', 'Your role controls which modules and actions you can use.', [details('Access boundaries', 'View access and permission to create, edit, or archive are separate capabilities.', 'Workspace data is scoped to your organization.', 'Reading Help Center articles does not change these permissions or expose another workspace’s records.')], { related: ['understanding-roles', 'permission-denied'] }),
];
