import { articleFactory, steps } from './types';
const a = articleFactory('troubleshooting');
export const troubleshootingArticles = [
  a('cannot-create-record', 'Why can’t I create a record?', 'Check access, required fields, and validation before trying again.', [steps('Confirm that your role has creation access for the module.', 'Complete fields marked required and review any validation messages.', 'Choose valid linked records from the same workspace.', 'Check that the save request finished successfully. If it failed, keep your entered information and report the visible error to your administrator.')], { related: ['validation-errors', 'permission-denied', 'creating-leads'] }),
  a('readonly-settings', 'Why can’t I edit a setting?', 'Some settings start read-only and others are protected.', [steps('In Profile Settings or General, select Edit before changing values.', 'Confirm you have settings editing access for organization changes.', 'Check whether the field is intentionally read-only, such as profile Email Address or the account form’s Country.', 'Save Changes when done, or Cancel to discard the draft.')], { related: ['profile-settings', 'general-settings', 'permission-denied'] }),
  a('missing-records', 'Why can’t I see a record?', 'Check filters, archive state, and permissions.', [steps('Clear the module search and filters, then check additional pages.', 'Check whether the record was archived or a lead was converted.', 'Use the module’s own search. Global deal search only examines loaded deals and all global result groups are limited.', 'Ask your administrator to confirm your workspace and access if the record remains missing.')], { related: ['global-search', 'archived-data'], keywords: ['missing', 'not found', 'record', 'invisible'] }),
  a('module-access', 'Why can’t I access a module?', 'Sidebar visibility depends on your assigned role.', [steps('Check whether the module is available in your current workspace.', 'Ask your administrator to review your assigned role and module view permission.', 'Refresh your session after an authorized access change.')], { notes: ['Opening an article or entering a page address does not grant module access.'], related: ['permission-denied', 'user-roles'] }),
  a('permission-denied', 'Permission denied', 'An action can require more access than viewing its records.', [steps('Note the action you attempted, such as create, edit, archive, or manage roles.', 'Ask your workspace administrator to check the corresponding capability on your role.', 'Retry only after the required access has been granted.')], { notes: ['Do not share passwords or another user’s session to work around a permission error.'], related: ['role-based-access', 'assigning-permissions'] }),
  a('phone-validation', 'Why does my phone number fail validation?', 'Use the PH (+63) input format in lead and contact forms.', [steps('Keep PH (+63) selected in the phone input.', 'Enter the 10-digit mobile part beginning with 9, such as 9123456789.', 'Do not add a leading 0 or repeat +63 in that local-number field.', 'Save. The international representation is +639123456789.')], { notes: ['These instructions apply to the dedicated lead/contact phone control. The profile and organization phone fields use different inputs.'], related: ['creating-leads', 'creating-contacts', 'profile-settings'], keywords: ['phone', 'mobile', '+63', 'validation', 'Philippines'] }),
  a('role-problems', 'Why can’t I create a custom role?', 'Check the role name and your authorization.', [steps('Enter a nonblank Role Name of no more than 50 characters.', 'Choose a unique name that is not reserved for a system role.', 'Review the permissions you intend to grant.', 'Ask your administrator to confirm role-management access if saving is denied.')], { related: ['creating-roles', 'role-restrictions', 'permission-denied'], keywords: ['create role', 'duplicate', 'name'] }),
  a('campaign-problems', 'Campaign problems', 'Check validation, sender configuration, and recipient outcomes.', [steps('Check the campaign name, content, and email subject, then review eligible audience counts and exclusions.', 'Ask your administrator to confirm the configured Brevo sender or TextBee gateway and your campaign sending permission.', 'Open the campaign report after sending. Submitted means provider acceptance; Pending or Interrupted outcomes need review.', 'If submission was interrupted, check provider records before sending again. Report the visible error and campaign name to your administrator.')], { notes: ['Uncertain delivery is preserved for review to prevent duplicate messages. Repeatedly pressing Send does not restart a submitted campaign.'], related: ['campaign-delivery', 'target-audiences', 'scheduling-campaigns'] }),
  a('validation-errors', 'Common validation errors', 'Correct common form inputs before saving.', [steps('Leads and Contacts: supply First Name and Last Name, and use a valid email when provided.', 'PH mobile inputs: enter 10 digits beginning with 9 after the fixed +63 prefix.', 'Accounts: supply Account Name; use a valid website URL and exactly nine Tax ID digits when provided.', 'Deals: select Pipeline and Stage, enter Title, and use a positive value when supplied.', 'Imports: use the import template and mapping requirements; these may require more fields than manual creation.')], { related: ['phone-validation', 'creating-accounts', 'creating-deals', 'importing-leads'] }),
];
