import { articleFactory, details, steps } from './types';
import { getAvailableActions, WORKFLOW_TRIGGERS } from '@leadcrm/shared';
const a = articleFactory('automation');
export const workflowArticles = [
  a('what-is-workflow', 'What is a Workflow?', 'Respond to supported CRM events with conditions and actions.', [details('The workflow model', 'Trigger → optional conditions → actions.', 'A workflow runs in the workspace where its triggering record belongs.', 'Draft or paused workflows do not automatically process new events. Configuration-only mock workspaces do not execute automation.')], { related: ['creating-workflows', 'workflow-triggers'] }),
  a('creating-workflows', 'Creating a Workflow', 'Build an automation with the options supported by LeadCRM.', [steps('Open Workflows and select Create workflow.', 'Start from an available recipe or configure your workflow.', 'Enter a name and select a trigger.', 'Add conditions if only some matching records should proceed.', 'Add and configure at least one action.', 'Choose Save draft, then review and test the configuration before activation.')], { notes: ['Workflow creation requires workflow creation access. The available actions depend on the triggering record type.'], related: ['workflow-triggers', 'workflow-conditions', 'workflow-actions'], keywords: ['create', 'automation', 'recipe'] }),
  a('workflow-triggers', 'Workflow Triggers', 'Choose the record event that starts an active workflow.', [details('Supported events', ...WORKFLOW_TRIGGERS.map(trigger => trigger.label)), details('Choosing an event', 'Choose a trigger that matches the record you want to automate. Its available condition fields and actions update accordingly.', 'Timer-based triggers, email opens, and link clicks are not offered by the current trigger catalog.')], { related: ['workflow-conditions', 'workflow-actions'] }),
  a('workflow-conditions', 'Workflow Conditions', 'Limit which triggering records proceed to actions.', [steps('Choose the trigger first.', 'Add conditions using only the fields offered for that trigger.', 'Choose the condition operator and enter a value of the expected type.', 'Set whether all or any conditions must match, then save and run a dry test.'), details('Fields and operators', 'The trigger determines the available standard and custom fields. Field types determine which operators and values are available.', 'Text comparisons include equals, not equals, contains, not contains, starts with, and ends with. Numeric comparisons require a numeric field.')], { notes: ['Update Fields offers its own supported field list and preserves the CRM module’s validation rules.'], related: ['workflow-testing', 'workflow-actions'] }),
  a('workflow-actions', 'Workflow Actions', 'Choose supported actions for the triggering record.', [details('Available actions', ...getAvailableActions().map(action => `${action.label}: ${action.description}`)), details('Assignment', 'Assign Agent and Create Task can select a user, role or group. Roles and groups assign one eligible person using round-robin, least workload, random, availability-based, capacity-based or sticky assignment. Configure the method inside the action.', 'Create Task can use the current record agent. Task assignees need Tasks access; CRM owners must meet the existing sales-agent rules.', 'Configure weekly shifts and unavailable members, default and per-member capacity limits, or a sticky fallback. Availability and capacity can filter other methods too. Group membership grants no permissions; Client Admin is excluded from automatic pools. If nobody qualifies, the action fails clearly.')], { notes: ['Workflow email requires a valid connected Gmail sender and recipient. SMS requires a configured sender and respects Do not contact.', 'Actions run immediately in order. Delay, parallel branches, approval gates and SLA timers are unavailable.', 'Notifications are handled by existing CRM and Task behavior; Send Notification and Send Campaign are retired workflow actions.'], related: ['activating-workflows', 'workflow-testing', 'email-templates'] }),
  a('activating-workflows', 'Activating a Workflow', 'Enable a valid workflow for future matching events.', [steps('Open the workflow and review its trigger, conditions, and action settings.', 'Resolve missing required action information.', 'Select Save and activate, or use Activate on a valid saved workflow.', 'Use Pause when you want to stop processing future matching events.')], { notes: ['Activation requires workflow activation permission and the permissions required by its actions. Archived workflows cannot be edited or activated.', 'Activation does not replay all existing records or historical events.'], related: ['workflow-history', 'workflow-testing'] }),
  a('workflow-testing', 'Testing a Workflow', 'Validate a saved configuration without changing records or sending messages.', [steps('Save the workflow and choose Test.', 'Select an existing sample record of the trigger’s record type in the workspace.', 'Select Run check.', 'Review the trigger match, condition results, assignment preview and validation message for each action.')], { notes: ['A dry test validates configuration; it does not replay a historical event or prove external delivery. Testing requires the real backend.'], related: ['workflow-history', 'workflow-troubleshooting'], keywords: ['dry run', 'test', 'sample'] }),
  a('workflow-history', 'Workflow History / Runs', 'Inspect recorded executions and action outcomes.', [steps('Open Workflows and select Runs for the workflow.', 'Select an execution to review its version, saved definition and steps.', 'Review the resolved assignee and any failed or skipped steps before changing the configuration.')], { notes: ['Definition versions change when the trigger, conditions or actions change. Pausing does not change the version. Older runs may not have a saved definition.', 'Membership changes affect future assignments only. Dry tests preview eligible assignment without advancing rotation.', 'No runs may mean that no new matching event has occurred since activation. Mock workspaces do not produce real executions.'], related: ['workflow-troubleshooting', 'workflow-testing'] }),
  a('workflow-troubleshooting', 'Troubleshooting Workflows', 'Check activation, conditions, and action requirements.', [steps('Check that the workflow is active and a supported new event occurred.', 'Review conditions and run a dry test.', 'Inspect Runs for the failed action.', 'For email, check that the selected Gmail sender is connected. For stage movement, check the destination and required lost reason.')], { related: ['workflow-actions', 'workflow-history', 'permission-denied'] }),
];
