import type { Pipeline, Deal } from '../types';

// ─── Pipelines ────────────────────────────────────────────────────────────────

export const MOCK_PIPELINES: Pipeline[] = [
  {
    id: 'pipe_sales',
    tenantId: 'tenant_demo',
    name: 'Sales Inquiries',
    stages: [
      { id: 'stage_lead',        name: 'Discovery',    order: 0, probability: 10 },
      { id: 'stage_assessment',  name: 'Assessment',   order: 1, probability: 25 },
      { id: 'stage_proposal',    name: 'Proposal',     order: 2, probability: 40 },
      { id: 'stage_negotiation', name: 'Negotiation',  order: 3, probability: 70 },
      { id: 'stage_won',         name: 'Closed Won',   order: 4, probability: 100 },
      { id: 'stage_lost',        name: 'Closed Lost',  order: 5, probability: 0 },
    ],
  },
  {
    id: 'pipe_tech',
    tenantId: 'tenant_demo',
    name: 'Technical Support',
    stages: [
      { id: 'stage_ticket',   name: 'Ticket Opened', order: 0, probability: 10 },
      { id: 'stage_review',   name: 'Under Review',  order: 1, probability: 40 },
      { id: 'stage_progress', name: 'In Progress',   order: 2, probability: 70 },
      { id: 'stage_resolved', name: 'Resolved',      order: 3, probability: 100 },
    ],
  },
  {
    id: 'pipe_project',
    tenantId: 'tenant_demo',
    name: 'Project Implementation',
    stages: [
      { id: 'stage_init',    name: 'Initiation', order: 0, probability: 20 },
      { id: 'stage_plan',    name: 'Planning',   order: 1, probability: 40 },
      { id: 'stage_exec',    name: 'Execution',  order: 2, probability: 75 },
      { id: 'stage_handoff', name: 'Handoff',    order: 3, probability: 95 },
    ],
  },
  {
    id: 'pipe_aftersales',
    tenantId: 'tenant_demo',
    name: 'After-sales Concerns',
    stages: [
      { id: 'stage_inquiry',    name: 'Inquiry',    order: 0, probability: 30 },
      { id: 'stage_followup',   name: 'Follow-up',  order: 1, probability: 60 },
      { id: 'stage_conclusion', name: 'Conclusion', order: 2, probability: 90 },
    ],
  },
];

// ─── Deals ────────────────────────────────────────────────────────────────────

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'HQ CCTV 64-Cam Surveillance System',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    contactId: 'lead_1',
    contactIds: ['lead_1'],
    companyId: 'org_1',
    value: 185000,
    priority: 'High',
    expectedCloseDate: '2026-08-15',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 0,
    createdAt: '2026-03-12T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-12T10:00:00.000Z', userId: 'user_sales_1', note: 'Discovery call completed' },
      { stageId: 'stage_assessment', timestamp: '2026-03-14T11:30:00.000Z', userId: 'user_sales_1', note: 'Completed physical site inspection' },
      { stageId: 'stage_proposal',   timestamp: '2026-03-18T09:00:00.000Z', userId: 'user_sales_1', note: 'Proposal and BOM submitted to management' },
    ],
  },
  {
    id: 'deal_2',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Biometric Access Control & Turnstiles',
    companyName: 'Nexus Digital',
    contactPerson: 'Robert Taylor',
    contactId: 'lead_6',
    contactIds: ['lead_6'],
    companyId: 'org_6',
    value: 98000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-05',
    leadSource: 'Inbound Web',
    customerType: 'New Business',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-03-18T14:30:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-03-18T14:30:00.000Z', userId: 'user_sales_1', note: 'Inbound lead qualified' },
      { stageId: 'stage_assessment',  timestamp: '2026-03-20T10:00:00.000Z', userId: 'user_sales_1', note: 'Door audit completed' },
      { stageId: 'stage_proposal',    timestamp: '2026-03-22T15:45:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_negotiation', timestamp: '2026-03-25T10:00:00.000Z', userId: 'user_sales_1', note: 'Final pricing terms review' },
    ],
  },
  {
    id: 'deal_3',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_proposal',
    title: 'Enterprise Wi-Fi 6E & 10G Backbone',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    contactId: 'lead_3',
    contactIds: ['lead_3'],
    companyId: 'org_3',
    value: 750000,
    priority: 'High',
    expectedCloseDate: '2026-08-28',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-22T09:15:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-22T09:15:00.000Z', userId: 'user_sales_3', note: 'RFP received' },
      { stageId: 'stage_assessment', timestamp: '2026-03-24T14:00:00.000Z', userId: 'user_sales_3', note: 'RF Heatmap survey completed' },
      { stageId: 'stage_proposal',   timestamp: '2026-03-26T11:00:00.000Z', userId: 'user_sales_3', note: 'Custom architecture proposal delivered' },
    ],
  },
  {
    id: 'deal_4',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Hybrid Cloud Migration & AWS Security',
    companyName: 'Globex Corporation',
    contactPerson: 'Jane Smith',
    contactId: 'lead_2',
    contactIds: ['lead_2'],
    companyId: 'org_2',
    value: 520000,
    priority: 'High',
    expectedCloseDate: '2026-09-10',
    leadSource: 'LinkedIn Outreach',
    customerType: 'New Business',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-03-25T16:45:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-25T16:45:00.000Z', userId: 'user_sales_2', note: 'Initial cloud assessment requested' },
      { stageId: 'stage_assessment', timestamp: '2026-03-26T10:00:00.000Z', userId: 'user_sales_2', note: 'Workload & dependency mapping started' },
    ],
  },
  {
    id: 'deal_5',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_won',
    title: 'Managed IT & 24/7 SLA Support Contract',
    companyName: 'Innovate Solutions',
    contactPerson: 'Sarah Johnson',
    contactId: 'lead_5',
    contactIds: ['lead_5'],
    companyId: 'org_5',
    value: 240000,
    priority: 'High',
    expectedCloseDate: '2026-06-15',
    leadSource: 'Partner Channel',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-02-01T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-02-01T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal',    timestamp: '2026-02-05T11:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_negotiation', timestamp: '2026-02-25T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_won',         timestamp: '2026-06-15T15:30:00.000Z', userId: 'user_sales_2', note: 'Annual SLA contract executed' },
    ],
  },
  {
    id: 'deal_6',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Structured Cabling Cat6A (300 Drops)',
    companyName: 'TechCorp Inc',
    contactPerson: 'Emily Davis',
    value: 145000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-20',
    leadSource: 'Trade Show',
    customerType: 'New Business',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-03-20T11:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-03-20T11:00:00.000Z', userId: 'user_sales_2', note: 'Blueprint review' },
      { stageId: 'stage_proposal', timestamp: '2026-03-23T14:00:00.000Z', userId: 'user_sales_2', note: 'BOQ & quotation sent' },
    ],
  },
  {
    id: 'deal_7',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_assessment',
    title: 'IP PBX System & 80 SIP Telephones',
    companyName: 'DataWorks',
    contactPerson: 'Michael Chen',
    contactId: 'lead_7',
    contactIds: ['lead_7'],
    companyId: 'org_7',
    value: 115000,
    priority: 'Medium',
    expectedCloseDate: '2026-09-01',
    leadSource: 'Cold Call',
    customerType: 'New Business',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-24T16:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-24T16:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_assessment', timestamp: '2026-03-26T10:00:00.000Z', userId: 'user_sales_3', note: 'SIP trunk audit initiated' },
    ],
  },
  {
    id: 'deal_lost_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_lost',
    title: 'FDAS Fire Detection & Alarm Retrofit',
    companyName: 'Initech',
    contactPerson: 'Bill Lumbergh',
    contactId: 'lead_4',
    contactIds: ['lead_4'],
    companyId: 'org_4',
    value: 45000,
    priority: 'Low',
    expectedCloseDate: '2026-05-10',
    assignedUserId: 'user_sales_1',
    lostReason: 'Prospect deferred FDAS compliance upgrade to FY2027 budget cycle.',
    leadSource: 'Cold Call',
    customerType: 'Existing Customer',
    order: 0,
    createdAt: '2026-02-15T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-02-15T14:00:00.000Z', userId: 'user_sales_1', note: 'Deal created' },
      { stageId: 'stage_proposal', timestamp: '2026-02-20T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_lost',     timestamp: '2026-05-10T15:00:00.000Z', userId: 'user_sales_1', note: 'Prospect deferred upgrade' },
    ],
  },
  {
    id: 'deal_9',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_aftersales',
    stageId: 'stage_won',
    title: 'Business Fiber 500Mbps Dedicated Line',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    contactId: 'lead_1',
    contactIds: ['lead_1'],
    companyId: 'org_1',
    value: 48000,
    priority: 'Medium',
    expectedCloseDate: '2026-04-10',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-03-01T09:00:00.000Z',
    history: [
      { stageId: 'stage_inquiry',    timestamp: '2026-03-01T09:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_followup',   timestamp: '2026-03-05T14:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_conclusion', timestamp: '2026-04-10T11:00:00.000Z', userId: 'user_sales_1', note: 'Fiber circuit activated' },
    ],
  },
  {
    id: 'deal_10',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Thermal Vision CCTV Lab Coverage',
    companyName: 'Cyberdyne Systems',
    contactPerson: 'Miles Dyson',
    contactId: 'lead_8',
    contactIds: ['lead_8'],
    companyId: 'org_8',
    value: 340000,
    priority: 'High',
    expectedCloseDate: '2026-08-30',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 0,
    createdAt: '2026-04-01T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-01T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_assessment', timestamp: '2026-04-05T11:00:00.000Z', userId: 'user_sales_1', note: 'Cleanroom audit completed' },
    ],
  },
  {
    id: 'deal_11',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_proposal',
    title: '10G Fiber Backbone & Core Switching',
    companyName: 'Wayne Enterprises',
    contactPerson: 'Lucius Fox',
    contactId: 'lead_9',
    contactIds: ['lead_9'],
    companyId: 'org_9',
    value: 165000,
    priority: 'High',
    expectedCloseDate: '2026-07-25',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-04-02T14:30:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-02T14:30:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-04-06T10:00:00.000Z', userId: 'user_sales_2', note: 'Architecture design submitted' },
    ],
  },
  {
    id: 'deal_12',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_lead',
    title: 'IP PBX System & 40 SIP Desk Phones',
    companyName: 'Oscorp Industries',
    contactPerson: 'Norman Osborn',
    contactId: 'lead_10',
    contactIds: ['lead_10'],
    companyId: 'org_10',
    value: 115000,
    priority: 'Medium',
    expectedCloseDate: '2026-09-15',
    leadSource: 'Cold Call',
    customerType: 'New Business',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-04-03T09:15:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-04-03T09:15:00.000Z', userId: 'user_sales_3', note: 'Initial inquiry' },
    ],
  },
  {
    id: 'deal_13',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Retinal & Facial Biometrics Tower Access',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    contactId: 'lead_11',
    contactIds: ['lead_11'],
    companyId: 'org_11',
    value: 640000,
    priority: 'High',
    expectedCloseDate: '2026-06-30',
    leadSource: 'LinkedIn',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-04-04T11:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-04T11:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_assessment', timestamp: '2026-04-08T14:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal',   timestamp: '2026-04-12T10:00:00.000Z', userId: 'user_sales_2', note: 'Custom proposal delivered' },
    ],
  },
  {
    id: 'deal_14',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Server Racks & Hot-Aisle Containment',
    companyName: 'Aperture Science',
    contactPerson: 'Cave Johnson',
    contactId: 'lead_12',
    contactIds: ['lead_12'],
    companyId: 'org_12',
    value: 300000,
    priority: 'High',
    expectedCloseDate: '2026-08-30',
    leadSource: 'Conference',
    customerType: 'New Business',
    assignedUserId: 'user_sales_1',
    order: 0,
    createdAt: '2026-04-05T16:45:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-05T16:45:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_assessment', timestamp: '2026-04-09T11:00:00.000Z', userId: 'user_sales_1', note: 'Facility cooling assessment started' },
    ],
  },
  {
    id: 'deal_15',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Night-Vision 4K CCTV Residence Security',
    companyName: 'Cyber Survival Net',
    contactPerson: 'Sarah Connor',
    contactId: 'lead_13',
    contactIds: ['lead_13'],
    value: 210000,
    priority: 'High',
    expectedCloseDate: '2026-06-15',
    leadSource: 'Referral',
    customerType: 'New Business',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-04-06T08:30:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-06T08:30:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_proposal', timestamp: '2026-04-10T15:00:00.000Z', userId: 'user_sales_3', note: 'Night-vision demo quotation delivered' },
    ],
  },
  {
    id: 'deal_16',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Subterranean Motion Sensor & Radar Grid',
    companyName: 'Wayne Estate',
    contactPerson: 'Bruce Wayne',
    contactId: 'lead_14',
    contactIds: ['lead_14'],
    value: 890000,
    priority: 'High',
    expectedCloseDate: '2026-07-10',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-04-07T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-04-07T14:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_assessment',  timestamp: '2026-04-09T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_negotiation', timestamp: '2026-04-14T11:00:00.000Z', userId: 'user_sales_2', note: 'Final contract terms review' },
    ],
  },
  {
    id: 'deal_17',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_lead',
    title: 'Apartment Smart Lock & Video Doorbell',
    companyName: 'Daily Bugle Press',
    contactPerson: 'Peter Parker',
    contactId: 'lead_15',
    contactIds: ['lead_15'],
    value: 12500,
    priority: 'Low',
    expectedCloseDate: '2026-05-25',
    leadSource: 'Web Form',
    customerType: 'New Business',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-04-08T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-04-08T10:00:00.000Z', userId: 'user_sales_3', note: 'Inquiry received' },
    ],
  },
  {
    id: 'deal_18',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Press Room High-Speed Fiber Routing',
    companyName: 'Daily Planet',
    contactPerson: 'Clark Kent',
    contactId: 'lead_16',
    contactIds: ['lead_16'],
    companyId: 'org_16',
    value: 165000,
    priority: 'High',
    expectedCloseDate: '2026-07-01',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 0,
    createdAt: '2026-04-09T09:15:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-09T09:15:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal', timestamp: '2026-04-12T14:00:00.000Z', userId: 'user_sales_1', note: 'Quotation delivered' },
    ],
  },
  {
    id: 'deal_19',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Museum Laser Security & Vibration Sensors',
    companyName: 'Themyscira Antiquities',
    contactPerson: 'Diana Prince',
    contactId: 'lead_17',
    contactIds: ['lead_17'],
    companyId: 'org_17',
    value: 280000,
    priority: 'High',
    expectedCloseDate: '2026-08-15',
    leadSource: 'Social Media Advertisement',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-04-10T11:45:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-04-10T11:45:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_assessment',  timestamp: '2026-04-12T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_negotiation', timestamp: '2026-04-15T09:00:00.000Z', userId: 'user_sales_2', note: 'Curator board review' },
    ],
  },
  {
    id: 'deal_20',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'CSI Forensics Lab Secured Data Cabinets',
    companyName: 'Central City PD',
    contactPerson: 'Barry Allen',
    contactId: 'lead_18',
    contactIds: ['lead_18'],
    companyId: 'org_18',
    value: 40000,
    priority: 'Medium',
    expectedCloseDate: '2026-06-30',
    leadSource: 'Cold Call',
    customerType: 'New Business',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-04-11T16:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-11T16:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_assessment', timestamp: '2026-04-14T11:00:00.000Z', userId: 'user_sales_3', note: 'Subnet isolation review' },
    ],
  },
  {
    id: 'deal_21',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_proposal',
    title: 'Marine Waterproof Fiber & Weather Radio',
    companyName: 'Amnesty Bay Lighthouse',
    contactPerson: 'Arthur Curry',
    contactId: 'lead_19',
    contactIds: ['lead_19'],
    companyId: 'org_19',
    value: 125000,
    priority: 'Medium',
    expectedCloseDate: '2026-07-20',
    leadSource: 'Web Form',
    customerType: 'New Business',
    assignedUserId: 'user_sales_1',
    order: 0,
    createdAt: '2026-04-12T13:30:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-12T13:30:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal', timestamp: '2026-04-15T14:00:00.000Z', userId: 'user_sales_1', note: 'Marine cable sample sent' },
    ],
  },
  {
    id: 'deal_22',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_won',
    title: 'Campus Smart IoT Automation Hub',
    companyName: 'Gotham City University',
    contactPerson: 'Victor Stone',
    contactId: 'lead_20',
    contactIds: ['lead_20'],
    value: 75000,
    priority: 'High',
    expectedCloseDate: '2026-04-30',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-04-13T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-04-13T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_won',  timestamp: '2026-04-30T16:00:00.000Z', userId: 'user_sales_2', note: 'IoT gateway deployed and tested' },
    ],
  },
  {
    id: 'deal_23',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Cat6A Structured Cabling (200 Drops)',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    contactId: 'lead_1',
    contactIds: ['lead_1'],
    companyId: 'org_1',
    value: 120000,
    priority: 'High',
    expectedCloseDate: '2026-09-01',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 2,
    createdAt: '2026-04-02T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-02T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal', timestamp: '2026-04-10T14:00:00.000Z', userId: 'user_sales_1' },
    ],
  },
  {
    id: 'deal_24',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Fortinet FortiGate Next-Gen Firewall',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    contactId: 'lead_1',
    contactIds: ['lead_1'],
    companyId: 'org_1',
    value: 95000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-20',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 3,
    createdAt: '2026-04-05T11:30:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-04-05T11:30:00.000Z', userId: 'user_sales_1' },
    ],
  },
  {
    id: 'deal_25',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Enterprise Wi-Fi 6 Access Points (30 Units)',
    companyName: 'Globex Corporation',
    contactPerson: 'Jane Smith',
    contactId: 'lead_2',
    contactIds: ['lead_2'],
    companyId: 'org_2',
    value: 145000,
    priority: 'High',
    expectedCloseDate: '2026-08-15',
    leadSource: 'LinkedIn Outreach',
    customerType: 'New Business',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-04-03T15:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-03T15:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-04-08T09:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_26',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_aftersales',
    stageId: 'stage_won',
    title: '24/7 Managed Network Monitoring SLA',
    companyName: 'Globex Corporation',
    contactPerson: 'Jane Smith',
    contactId: 'lead_2',
    contactIds: ['lead_2'],
    companyId: 'org_2',
    value: 85000,
    priority: 'Medium',
    expectedCloseDate: '2026-05-10',
    leadSource: 'LinkedIn Outreach',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 2,
    createdAt: '2026-03-28T10:00:00.000Z',
    history: [
      { stageId: 'stage_inquiry', timestamp: '2026-03-28T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_won',     timestamp: '2026-05-10T14:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_27',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_exec',
    title: 'Data Center Server Rack Backbone & Cooling Pods',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    contactId: 'lead_3',
    contactIds: ['lead_3'],
    companyId: 'org_3',
    value: 380000,
    priority: 'High',
    expectedCloseDate: '2026-07-30',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_3',
    order: 1,
    createdAt: '2026-03-25T14:00:00.000Z',
    history: [
      { stageId: 'stage_init', timestamp: '2026-03-25T14:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_exec', timestamp: '2026-04-10T11:00:00.000Z', userId: 'user_sales_3' },
    ],
  },
  {
    id: 'deal_28',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Biometric Retinal Scanner Turnstile Speedgates',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    contactId: 'lead_3',
    contactIds: ['lead_3'],
    companyId: 'org_3',
    value: 290000,
    priority: 'High',
    expectedCloseDate: '2026-08-10',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_3',
    order: 2,
    createdAt: '2026-03-29T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-03-29T09:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_negotiation', timestamp: '2026-04-12T16:00:00.000Z', userId: 'user_sales_3' },
    ],
  },
  {
    id: 'deal_29',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'IP PBX 100 SIP Extension Telephony System',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    contactId: 'lead_3',
    contactIds: ['lead_3'],
    companyId: 'org_3',
    value: 150000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-25',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_3',
    order: 3,
    createdAt: '2026-04-01T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-01T10:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_proposal', timestamp: '2026-04-07T14:30:00.000Z', userId: 'user_sales_3' },
    ],
  },
  {
    id: 'deal_30',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'AI Perimeter Defense & Thermal Radar Grid',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    contactId: 'lead_3',
    contactIds: ['lead_3'],
    companyId: 'org_3',
    value: 680000,
    priority: 'High',
    expectedCloseDate: '2026-09-15',
    leadSource: 'Website',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_3',
    order: 4,
    createdAt: '2026-04-04T11:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-04T11:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_assessment', timestamp: '2026-04-11T10:00:00.000Z', userId: 'user_sales_3' },
    ],
  },
  {
    id: 'deal_31',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Enterprise High-Density Blade Servers',
    companyName: 'Umbrella Corp',
    contactPerson: 'Albert Wesker',
    contactId: 'lead_5',
    contactIds: ['lead_5'],
    companyId: 'org_5',
    value: 250000,
    priority: 'High',
    expectedCloseDate: '2026-08-20',
    leadSource: 'Conference',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-03-10T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-03-10T14:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-03-18T10:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_32',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Perimeter Smart Card Access & Turnstiles',
    companyName: 'Umbrella Corp',
    contactPerson: 'Albert Wesker',
    contactId: 'lead_5',
    contactIds: ['lead_5'],
    companyId: 'org_5',
    value: 175000,
    priority: 'Medium',
    expectedCloseDate: '2026-09-05',
    leadSource: 'Conference',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 2,
    createdAt: '2026-03-15T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-15T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_assessment', timestamp: '2026-03-22T11:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_33',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Subnet Firewall & Intrusion Prevention System',
    companyName: 'Cyberdyne Systems',
    contactPerson: 'Miles Dyson',
    contactId: 'lead_8',
    contactIds: ['lead_8'],
    companyId: 'org_8',
    value: 180000,
    priority: 'High',
    expectedCloseDate: '2026-08-10',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-04-03T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-03T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal', timestamp: '2026-04-09T15:00:00.000Z', userId: 'user_sales_1' },
    ],
  },
  {
    id: 'deal_34',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_plan',
    title: 'HQ Data Center Fiber Interconnect Link',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    contactId: 'lead_11',
    contactIds: ['lead_11'],
    companyId: 'org_11',
    value: 420000,
    priority: 'High',
    expectedCloseDate: '2026-07-20',
    leadSource: 'LinkedIn',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-04-05T09:00:00.000Z',
    history: [
      { stageId: 'stage_init', timestamp: '2026-04-05T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_plan', timestamp: '2026-04-12T14:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_35',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: '4K CCTV Surveillance & AI Analytics Grid',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    contactId: 'lead_11',
    contactIds: ['lead_11'],
    companyId: 'org_11',
    value: 210000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-30',
    leadSource: 'LinkedIn',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 2,
    createdAt: '2026-04-07T11:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-07T11:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_assessment', timestamp: '2026-04-13T10:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_36',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_aftersales',
    stageId: 'stage_followup',
    title: 'Cloud Backup & Disaster Recovery Storage Retainer',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    contactId: 'lead_11',
    contactIds: ['lead_11'],
    companyId: 'org_11',
    value: 350000,
    priority: 'High',
    expectedCloseDate: '2026-06-15',
    leadSource: 'LinkedIn',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 3,
    createdAt: '2026-03-30T16:00:00.000Z',
    history: [
      { stageId: 'stage_inquiry',  timestamp: '2026-03-30T16:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_followup', timestamp: '2026-04-08T11:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_37',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Private Estate Thermal Night-Vision Grid',
    companyName: 'Wayne Estate',
    contactPerson: 'Bruce Wayne',
    contactId: 'lead_14',
    contactIds: ['lead_14'],
    value: 450000,
    priority: 'High',
    expectedCloseDate: '2026-08-05',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-04-08T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-08T14:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-04-14T09:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
  {
    id: 'deal_38',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_assessment',
    title: 'Editorial Floor VoIP Handsets & Headsets',
    companyName: 'Daily Planet',
    contactPerson: 'Clark Kent',
    contactId: 'lead_16',
    contactIds: ['lead_16'],
    companyId: 'org_16',
    value: 55000,
    priority: 'Medium',
    expectedCloseDate: '2026-07-20',
    leadSource: 'Referral',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-04-10T11:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-04-10T11:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_assessment', timestamp: '2026-04-15T10:00:00.000Z', userId: 'user_sales_1' },
    ],
  },
  {
    id: 'deal_39',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Vault Climate & Environmental Sensor Network',
    companyName: 'Themyscira Antiquities',
    contactPerson: 'Diana Prince',
    contactId: 'lead_17',
    contactIds: ['lead_17'],
    companyId: 'org_17',
    value: 110000,
    priority: 'Medium',
    expectedCloseDate: '2026-08-28',
    leadSource: 'Social Media Advertisement',
    customerType: 'Existing Customer',
    assignedUserId: 'user_sales_2',
    order: 1,
    createdAt: '2026-04-11T15:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-04-11T15:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-04-16T11:00:00.000Z', userId: 'user_sales_2' },
    ],
  },
];

