import type { Tenant, User, Permission, RoleDefinition } from '../types';

// ─── Tenants ─────────────────────────────────────────────────────────────────

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant_demo',
    name: 'Demo Corp Solutions',
    industry: 'IT Solutions',
    size: '50-200',
    email: 'contact@democorp.com',
    phone: '+1 (555) 123-4567',
    address: '123 Tech Lane, Silicon Valley, CA',
    status: 'active',
    approvalStep: 'completed',
    environment: 'production',
    createdAt: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'tenant_2',
    name: 'Global Logistics Inc.',
    industry: 'Logistics',
    size: '500+',
    email: 'info@globallogistics.com',
    phone: '+1 (555) 987-6543',
    address: '456 Freight Blvd, Chicago, IL',
    status: 'active',
    approvalStep: 'completed',
    environment: 'both',
    createdAt: '2025-02-20T10:30:00.000Z',
  },
  {
    id: 'tenant_3',
    name: 'NextGen Healthcare',
    industry: 'Healthcare',
    size: '200-500',
    email: 'partners@nextgenhealth.com',
    phone: '+1 (555) 456-7890',
    address: '789 Medical Parkway, Boston, MA',
    status: 'pending',
    approvalStep: 'basic',
    environment: 'none',
    createdAt: '2026-03-28T14:15:00.000Z',
  },
  {
    id: 'tenant_4',
    name: 'Starlight Media',
    industry: 'Media & Entertainment',
    size: '10-50',
    email: 'hello@starlightmedia.net',
    phone: '+1 (555) 234-5678',
    address: '321 Creative Studio, Austin, TX',
    status: 'suspended',
    approvalStep: 'completed',
    environment: 'production',
    createdAt: '2025-06-10T09:45:00.000Z',
  },
];

// ─── Users ────────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: 'user_super',
    tenantId: 'system',
    firstName: 'System',
    lastName: 'Admin',
    email: 'super@leadcrm.com',
    role: 'System Admin',
    status: 'active',
  },
  {
    // Primary System Admin — email matches SYSTEM_ADMIN_EMAIL seed default (admin@gmail.com)
    id: 'user_system_admin',
    tenantId: 'system',
    firstName: 'System',
    lastName: 'Admin',
    email: 'admin@gmail.com',
    role: 'System Admin',
    status: 'active',
  },
  {
    id: 'user_client_admin',
    tenantId: 'tenant_demo',
    firstName: 'Alice',
    lastName: 'Admin',
    email: 'admin@democorp.com',
    role: 'Client Admin',
    status: 'active',
    team: 'Management',
  },
  {
    id: 'user_sales_1',
    tenantId: 'tenant_demo',
    firstName: 'Bob',
    lastName: 'Sales',
    email: 'bob@democorp.com',
    role: 'User',
    status: 'active',
    team: 'Sales Team A',
  },
  {
    id: 'user_sales_2',
    tenantId: 'tenant_demo',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.j@democorp.com',
    role: 'User',
    status: 'active',
    team: 'Sales Team A',
  },
  {
    id: 'user_sales_3',
    tenantId: 'tenant_demo',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'm.chen@democorp.com',
    role: 'User',
    status: 'active',
    team: 'Sales Team B',
  },
  {
    id: 'user_viewer_1',
    tenantId: 'tenant_demo',
    firstName: 'David',
    lastName: 'Manager',
    email: 'david.m@acmecorp.com',
    role: 'Guest',
    status: 'pending',
    team: 'Management',
  },
  {
    id: 'user_guest',
    tenantId: 'tenant_demo',
    firstName: 'Guest',
    lastName: 'User',
    email: 'guest@democorp.com',
    role: 'Guest',
    status: 'active',
  },
];

// ─── Permissions ─────────────────────────────────────────────────────────────

export const MOCK_PERMISSIONS: Permission[] = [
  { id: 'p1',      name: 'View Dashboard',       category: 'Dashboard',  description: 'Access to the main dashboard' },
  { id: 'p2',      name: 'View All Contacts',     category: 'Contacts',   description: 'View all contact lists across the organization' },
  { id: 'p2_own',  name: 'View Own Contacts',     category: 'Contacts',   description: 'View only assigned contacts' },
  { id: 'p3',      name: 'Create Contacts',       category: 'Contacts',   description: 'Add new contacts' },
  { id: 'p4',      name: 'Edit All Contacts',     category: 'Contacts',   description: 'Modify any existing contacts' },
  { id: 'p4_own',  name: 'Edit Own Contacts',     category: 'Contacts',   description: 'Modify only assigned contacts' },
  { id: 'p5',      name: 'Delete All Contacts',   category: 'Contacts',   description: 'Remove any contacts' },
  { id: 'p5_own',  name: 'Delete Own Contacts',   category: 'Contacts',   description: 'Remove only assigned contacts' },
  { id: 'p6',      name: 'Export Contacts',       category: 'Contacts',   description: 'Export contacts to CSV' },
  { id: 'p7',      name: 'View All Deals',        category: 'Deals',      description: 'View all deal pipelines across the organization' },
  { id: 'p7_own',  name: 'View Own Deals',        category: 'Deals',      description: 'View only assigned deals' },
  { id: 'p8',      name: 'Create Deals',          category: 'Deals',      description: 'Add new deals' },
  { id: 'p9',      name: 'Edit All Deals',        category: 'Deals',      description: 'Modify any existing deals' },
  { id: 'p9_own',  name: 'Edit Own Deals',        category: 'Deals',      description: 'Modify only assigned deals' },
  { id: 'p10',     name: 'Delete All Deals',      category: 'Deals',      description: 'Remove any deals' },
  { id: 'p10_own', name: 'Delete Own Deals',      category: 'Deals',      description: 'Remove only assigned deals' },
  { id: 'p11',     name: 'Manage Pipelines',      category: 'Deals',      description: 'Configure pipeline stages' },
  { id: 'p12',     name: 'View Workflows',        category: 'Workflows',  description: 'View automation workflows' },
  { id: 'p13',     name: 'Create Workflows',      category: 'Workflows',  description: 'Add new workflows' },
  { id: 'p14',     name: 'Edit Workflows',        category: 'Workflows',  description: 'Modify existing workflows' },
  { id: 'p15',     name: 'Delete Workflows',      category: 'Workflows',  description: 'Remove workflows' },
  { id: 'p16',     name: 'Execute Workflows',     category: 'Workflows',  description: 'Manually run workflows' },
  { id: 'p17',     name: 'View Campaigns',        category: 'Campaigns',  description: 'View marketing campaigns' },
  { id: 'p18',     name: 'Create Campaigns',      category: 'Campaigns',  description: 'Add new campaigns' },
  { id: 'p19',     name: 'Edit Campaigns',        category: 'Campaigns',  description: 'Modify existing campaigns' },
  { id: 'p20',     name: 'Delete Campaigns',      category: 'Campaigns',  description: 'Remove campaigns' },
  { id: 'p21',     name: 'Send Campaigns',        category: 'Campaigns',  description: 'Trigger campaign delivery' },
  { id: 'p22',     name: 'View Users',            category: 'Users',      description: 'View team members' },
  { id: 'p23',     name: 'Create Users',          category: 'Users',      description: 'Add new team members' },
  { id: 'p24',     name: 'Edit Users',            category: 'Users',      description: 'Modify user details' },
  { id: 'p25',     name: 'Delete Users',          category: 'Users',      description: 'Remove team members' },
  { id: 'p26',     name: 'Manage Roles',          category: 'Users',      description: 'Configure roles and permissions' },
  { id: 'p27',     name: 'View Settings',         category: 'Settings',   description: 'Access organization settings' },
  { id: 'p28',     name: 'Edit Settings',         category: 'Settings',   description: 'Modify organization settings' },
  { id: 'p29',     name: 'Manage Billing',        category: 'Settings',   description: 'View and pay invoices' },
  { id: 'p30',     name: 'View Audit Logs',       category: 'Settings',   description: 'Access system activity logs' },
  { id: 'p31',     name: 'View Reports',          category: 'Reports',    description: 'Access analytics reports' },
  { id: 'p32',     name: 'Create Reports',        category: 'Reports',    description: 'Build custom reports' },
  { id: 'p33',     name: 'Export Reports',        category: 'Reports',    description: 'Export report data' },
  { id: 'p34',     name: 'Manage Dashboard',      category: 'Dashboard',  description: 'Customize dashboard layout and widgets' },
  { id: 'p35',     name: 'View Inventory',        category: 'Inventory',  description: 'View stock and inventory levels' },
  { id: 'p36',     name: 'Manage Inventory',      category: 'Inventory',  description: 'Add, edit, or delete inventory items' },
  { id: 'p37',     name: 'View Assets',           category: 'Assets',     description: 'View installed client assets' },
  { id: 'p38',     name: 'Manage Assets',         category: 'Assets',     description: 'Register or modify client assets' },
];

// ─── Roles ────────────────────────────────────────────────────────────────────

export const MOCK_ROLES: RoleDefinition[] = [
  {
    id: 'r1',
    tenantId: 'tenant_demo',
    name: 'Client Admin',
    description: 'Full tenant ownership. Manages users, roles, billing, and all CRM data.',
    isSystemRole: true,
    userCount: 1,
    permissions: MOCK_PERMISSIONS.map(p => p.id),
    updatedAt: '1/1/2026',
  },
  {
    id: 'r3',
    tenantId: 'tenant_demo',
    name: 'User',
    description: 'Standard access for everyday operations, sales, and reporting.',
    isSystemRole: true,
    userCount: 3,
    permissions: ['p1','p2_own','p3','p4_own','p7_own','p8','p9_own','p12','p17','p31'],
    updatedAt: '1/1/2026',
  },
  {
    id: 'r4',
    tenantId: 'tenant_demo',
    name: 'Guest',
    description: 'Free sandbox plan. Full CRM CRUD (leads, contacts, deals, tasks). Limited to 100 contacts and 3 team members. Automation and campaigns require a paid plan.',
    isSystemRole: true,
    userCount: 1,
    // Free plan: full CRUD on contacts/accounts (p2-p6) and deals (p7-p10).
    // Campaigns (p17) and workflows (p12) stay view-only — paid features.
    permissions: ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10','p12','p17'],
    updatedAt: '1/1/2026',
  },
  {
    id: 'rc1',
    tenantId: 'tenant_demo',
    name: 'Intern',
    description: 'Limited access for learning and basic tasks',
    isSystemRole: false,
    userCount: 2,
    permissions: ['p1', 'p2', 'p7', 'p12'],
    updatedAt: '4/10/2026',
  },
  {
    id: 'rc2',
    tenantId: 'tenant_demo',
    name: 'External Contractor',
    description: 'Restricted CRM access for external consultants',
    isSystemRole: false,
    userCount: 1,
    permissions: ['p1', 'p7_own', 'p12'],
    updatedAt: '4/12/2026',
  },
];
