import type { Task } from '../types';

export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    tenantId: 'tenant_demo',
    dealId: 'deal_1',
    title: 'Initial Site Survey',
    description: 'Conduct a physical survey of the client site for CCTV placement and cable pathing.',
    status: 'completed',
    dueDate: '2026-03-15',
    assignedUserId: 'user_sales_2',
    createdAt: '2026-03-12T10:00:00.000Z',
    priority: 'Medium',
  },
  {
    id: 'task_2',
    tenantId: 'tenant_demo',
    dealId: 'deal_3',
    title: 'Proposal Review',
    description: 'Review the enterprise solution proposal with the legal team and regional stakeholders.',
    status: 'pending',
    dueDate: '2026-04-05',
    assignedUserId: 'user_sales_3',
    createdAt: '2026-03-22T09:15:00.000Z',
    priority: 'High',
  },
  {
    id: 'task_3',
    tenantId: 'tenant_demo',
    title: 'Hardware Order Placement',
    description: 'Execute procurement order for fiber switches, network cables, and router modules.',
    status: 'in_progress',
    dueDate: '2026-06-15',
    assignedUserId: 'user_sales_2',
    createdAt: '2026-05-25T11:00:00.000Z',
    priority: 'High',
  },
  {
    id: 'task_4',
    tenantId: 'tenant_demo',
    title: 'Draft User Manual',
    description: 'Create draft user manuals and handbook guides for custom VoIP lines configuration.',
    status: 'pending',
    dueDate: '2026-06-30',
    assignedUserId: 'user_sales_1',
    createdAt: '2026-05-28T14:30:00.000Z',
    priority: 'Low',
  },
];
