import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * seedSandboxData — seeds isolated, realistic CRM data into a guest sandbox tenant.
 *
 * Design principles:
 * - Fully tenant-agnostic: every record uses the passed tenantId, no hardcoded values.
 * - All IDs auto-generated by Prisma (@default(uuid())) — no hardcoded UUIDs.
 * - Idempotent: returns early if the tenant already has CRM records.
 * - Wrapped in a single $transaction so failure is atomic.
 * - Does NOT create a pipeline — one is already created during registerGuest().
 *   It finds the existing default pipeline and uses its stages.
 * - Activities follow the exactly-one-FK rule (link to dealId only).
 *
 * Call site: registerGuest() in auth.service.ts — awaited synchronously before
 * returning the registration response so the sandbox is fully populated on first login.
 */
export async function seedSandboxData(tenantId: string, userId: string): Promise<void> {
  // Idempotency check: if any Account exists for this tenant, we are already seeded.
  // The transaction in registerGuest() creates one Account; seedSandboxData creates
  // additional ones. Checking count > 0 means any prior seeding prevents a re-run.
  const existingCount = await prisma.account.count({ where: { tenantId } });
  if (existingCount > 0) {
    return; // Already seeded — safe to call multiple times
  }

  // Resolve the pipeline created during registerGuest() transaction.
  // That transaction always creates a default pipeline with stages.
  const existingPipeline = await prisma.pipeline.findFirst({
    where: { tenantId, isDefault: true, isArchived: false },
    include: { stages: { orderBy: { order: 'asc' } } },
  });

  if (!existingPipeline || existingPipeline.stages.length === 0) {
    throw new Error(
      `[Sandbox] No default pipeline found for tenant ${tenantId}. ` +
      'The registerGuest() transaction must run before seedSandboxData().',
    );
  }

  // Map stage names to stage records (case-insensitive)
  const stageByName = (name: string) =>
    existingPipeline.stages.find(s => s.name.toLowerCase() === name.toLowerCase())
    ?? existingPipeline.stages[0]; // fallback to first stage

  const stageInquiry    = stageByName('Lead');
  const stageContacted  = stageByName('Contacted');
  const stageQualified  = stageByName('Qualified');

  await prisma.$transaction(async (tx) => {
    // ── 1. Account ─────────────────────────────────────────────────────────
    const account = await tx.account.create({
      data: {
        tenantId,
        assignedUserId: userId,
        name:           'Acme Corporation',
        industry:       'Information Technology',
        customerType:   'Active Customer',
        size:           '51-200',
        website:        'https://acme-corp.example.com',
        country:        'Philippines',
      } as never,
    });

    // ── 2. Contacts — all linked to Acme via accountId (ADR-001) ───────────
    const [contactJohn, contactMaria, contactDavid] = await Promise.all([
      tx.contact.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          ownerId:       userId,
          firstName:     'John',
          lastName:      'Smith',
          email:         'john.smith@acme-corp.example.com',
          phone:         '+63 917 000 0001',
          jobTitle:      'Chief Executive Officer',
          status:        'HOT',
          score:         90,
          source:        'Referral',
          productInterests: ['CRM Enterprise'],
        } as never,
      }),
      tx.contact.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          ownerId:       userId,
          firstName:     'Maria',
          lastName:      'Lee',
          email:         'maria.lee@acme-corp.example.com',
          phone:         '+63 917 000 0002',
          jobTitle:      'IT Manager',
          status:        'WARM',
          score:         72,
          source:        'Website',
          productInterests: ['CRM Pro', 'Workflow Automation'],
        } as never,
      }),
      tx.contact.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          ownerId:       userId,
          firstName:     'David',
          lastName:      'Park',
          email:         'david.park@acme-corp.example.com',
          phone:         '+63 917 000 0003',
          jobTitle:      'Procurement Officer',
          status:        'COLD',
          score:         45,
          source:        'LinkedIn',
        } as never,
      }),
    ]);

    // ── 3. Leads — linked to Acme and each contact ─────────────────────────
    const [leadJohn, leadMaria, leadDavid] = await Promise.all([
      tx.lead.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          createdById:   userId,
          firstName:     contactJohn.firstName,
          lastName:      contactJohn.lastName,
          email:         contactJohn.email,
          phone:         contactJohn.phone,
          companyName:   account.name,
          status:        'Qualified',
          source:        'Referral',
        },
      }),
      tx.lead.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          createdById:   userId,
          firstName:     contactMaria.firstName,
          lastName:      contactMaria.lastName,
          email:         contactMaria.email,
          phone:         contactMaria.phone,
          companyName:   account.name,
          status:        'Contacted',
          source:        'Website',
        },
      }),
      tx.lead.create({
        data: {
          tenantId,
          accountId:     account.id,
          assignedUserId: userId,
          createdById:   userId,
          firstName:     contactDavid.firstName,
          lastName:      contactDavid.lastName,
          email:         contactDavid.email,
          phone:         contactDavid.phone,
          companyName:   account.name,
          status:        'Inquiry',
          source:        'LinkedIn',
        },
      }),
    ]);

    // ── 4. Deals — linked to Account, Contact (legacy FK) and Lead (LeadDeal junction) ─
    const [deal1, deal2, deal3] = await Promise.all([
      tx.deal.create({
        data: {
          tenantId,
          pipelineId:    existingPipeline.id,
          stageId:       stageQualified.id,
          accountId:     account.id,
          customerId:    contactJohn.id,
          assignedUserId: userId,
          ownerId:       userId,
          title:         'Acme CRM License Deal',
          value:         45000,
          currency:      'PHP',
          priority:      'HIGH',
          expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        } as never,
      }),
      tx.deal.create({
        data: {
          tenantId,
          pipelineId:    existingPipeline.id,
          stageId:       stageContacted.id,
          accountId:     account.id,
          customerId:    contactMaria.id,
          assignedUserId: userId,
          ownerId:       userId,
          title:         'Acme Support Package',
          value:         12000,
          currency:      'PHP',
          priority:      'MEDIUM',
          expectedCloseDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        } as never,
      }),
      tx.deal.create({
        data: {
          tenantId,
          pipelineId:    existingPipeline.id,
          stageId:       stageInquiry.id,
          accountId:     account.id,
          customerId:    contactDavid.id,
          assignedUserId: userId,
          ownerId:       userId,
          title:         'Acme Marketing Suite',
          value:         28000,
          currency:      'PHP',
          priority:      'LOW',
          expectedCloseDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        } as never,
      }),
    ]);

    // ── 5. ContactDeal junctions (canonical multi-contact deal path) ────────
    await Promise.all([
      tx.contactDeal.create({
        data: { tenantId, dealId: deal1.id, contactId: contactJohn.id, addedById: userId } as never,
      }),
      tx.contactDeal.create({
        data: { tenantId, dealId: deal2.id, contactId: contactMaria.id, addedById: userId } as never,
      }),
      tx.contactDeal.create({
        data: { tenantId, dealId: deal3.id, contactId: contactDavid.id, addedById: userId } as never,
      }),
    ]);

    // ── 6. LeadDeal junctions ───────────────────────────────────────────────
    await Promise.all([
      tx.leadDeal.create({
        data: { tenantId, dealId: deal1.id, leadId: leadJohn.id, addedById: userId } as never,
      }),
      tx.leadDeal.create({
        data: { tenantId, dealId: deal2.id, leadId: leadMaria.id, addedById: userId } as never,
      }),
      tx.leadDeal.create({
        data: { tenantId, dealId: deal3.id, leadId: leadDavid.id, addedById: userId } as never,
      }),
    ]);

    // ── 7. Activities — exactly one FK per activity (dealId only per the Activity rule) ─
    await Promise.all([
      tx.activity.create({
        data: {
          tenantId,
          createdById: userId,
          type:        'call',
          title:       'Discovery call — Acme CRM License Deal',
          dealId:      deal1.id,
        },
      }),
      tx.activity.create({
        data: {
          tenantId,
          createdById: userId,
          type:        'meeting',
          title:       'Product demo scheduled — Acme Support Package',
          dealId:      deal2.id,
        },
      }),
      tx.activity.create({
        data: {
          tenantId,
          createdById: userId,
          type:        'email',
          title:       'Proposal sent — Acme Marketing Suite',
          dealId:      deal3.id,
        },
      }),
    ]);
  });

  console.log(`[Sandbox] Seeded CRM data for tenant ${tenantId}: 1 Account, 3 Contacts, 3 Leads, 3 Deals, 3 Activities.`);
}

// ── Standalone runner ─────────────────────────────────────────────────────
if (require.main === module) {
  const tenantId = process.argv[2];
  const userId   = process.argv[3];
  if (!tenantId || !userId) {
    console.error('Usage: ts-node sandbox.seed.ts <tenantId> <userId>');
    process.exit(1);
  }
  seedSandboxData(tenantId, userId)
    .catch((err) => { console.error('[Sandbox] Error:', err); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
