import React from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { WorkflowExecutionLogModal } from './workflow-execution-log-modal';
import { workflowsApi } from '@/shared/services/workflows.api';
vi.mock('@/shared/services/workflows.api', () => ({ workflowsApi: { getExecutions: vi.fn() } }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
const run = { id: 'run', status: 'completed', startedAt: '2026-10-01T12:00:00Z', completedAt: '2026-10-01T12:01:00Z', entityType: 'lead', trigger: { payload: { recordName: 'Ada Lovelace' }, triggerType: 'lead_created' }, steps: [{ id: 'step', stepIndex: 0, actionType: 'create_task', status: 'completed' }] };
it('keeps runs, action order, refresh and pagination in the record Sheet', async () => {
  vi.mocked(workflowsApi.getExecutions).mockResolvedValue({ data: Array.from({ length: 25 }, (_, i) => ({ ...run, id: `run-${i}` })) } as never);
  const close = vi.fn();
  render(<WorkflowExecutionLogModal workflowId="wf" name="Follow up" status="Active" onClose={close} />);
  expect(screen.getByRole('status', { name: 'Loading workflow runs' })).toBeTruthy();
  const dialog = await screen.findByRole('dialog', { name: 'Runs — Follow up' });
  expect(dialog.className).toContain('right-0');
  expect(dialog.className).toContain('sm:max-w-[480px]');
  await waitFor(() => expect(dialog.querySelectorAll('details')).toHaveLength(25));
  const details = dialog.querySelector('details')!;
  fireEvent.click(details.querySelector('summary')!);
  expect(details.textContent).toContain('Ada Lovelace');
  expect(details.textContent).toContain('1. Create Task — completed');
  fireEvent.click(screen.getByRole('button', { name: 'Next' }));
  await waitFor(() => expect(workflowsApi.getExecutions).toHaveBeenLastCalledWith('wf', 2));
  await waitFor(() => expect((screen.getByRole('button', { name: 'Refresh activity' }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Refresh activity' }));
  await waitFor(() => expect(workflowsApi.getExecutions).toHaveBeenCalledTimes(3));
  fireEvent.click(screen.getByRole('button', { name: 'Close workflow runs' }));
  expect(close).toHaveBeenCalledOnce();
});
