-- Extend module rows in place. Preserve RoleDefinition, UserRole, and all users.
BEGIN;
ALTER TABLE "RolePermission"
  ADD COLUMN "canArchive" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canImport" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canManageStages" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canComplete" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canAssign" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canSend" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canDuplicate" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canViewReports" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canActivate" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canViewRuns" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canPublish" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canViewSubmissions" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canViewClosedWon" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canDisable" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "canRestore" BOOLEAN NOT NULL DEFAULT false;

-- Split historical shared access into the existing independent modules.
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':accounts'), p."tenantId", p."roleId", 'accounts', p."canView", p."canCreate", p."canEdit", p."canDelete" FROM "RolePermission" p WHERE p."module" = 'organizations'
ON CONFLICT ("roleId","module") DO UPDATE SET
  "canView" = "RolePermission"."canView" OR EXCLUDED."canView",
  "canCreate" = "RolePermission"."canCreate" OR EXCLUDED."canCreate",
  "canEdit" = "RolePermission"."canEdit" OR EXCLUDED."canEdit",
  "canDelete" = "RolePermission"."canDelete" OR EXCLUDED."canDelete";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':leads'), p."tenantId", p."roleId", 'leads', p."canView", p."canCreate", p."canEdit", p."canDelete" FROM "RolePermission" p WHERE p."module" = 'contacts'
ON CONFLICT ("roleId","module") DO NOTHING;
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':tasks'), p."tenantId", p."roleId", 'tasks', p."canView", p."canCreate", p."canEdit", p."canDelete" FROM "RolePermission" p WHERE p."module" = 'deals'
ON CONFLICT ("roleId","module") DO NOTHING;
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':forms'), p."tenantId", p."roleId", 'forms', p."canView", p."canCreate", p."canEdit", p."canDelete" FROM "RolePermission" p WHERE p."module" = 'campaigns'
ON CONFLICT ("roleId","module") DO NOTHING;
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':products'), p."tenantId", p."roleId", 'products', p."canView", false, false, false FROM "RolePermission" p WHERE p."module" = 'settings'
ON CONFLICT ("roleId","module") DO NOTHING;
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete")
SELECT md5(p."id" || ':custom_fields'), p."tenantId", p."roleId", 'custom_fields', p."canView", false, false, false FROM "RolePermission" p WHERE p."module" = 'settings'
ON CONFLICT ("roleId","module") DO NOTHING;

-- Only archive semantics are renamed. Newly separated sensitive actions default off.
UPDATE "RolePermission" SET "canArchive" = "canDelete" WHERE "module" IN ('leads','contacts','accounts','deals','tasks','campaigns','workflows','products','users','roles');
UPDATE "RolePermission" SET "canImport" = "canCreate" WHERE "module" IN ('leads','contacts','accounts');
DELETE FROM "RolePermission" WHERE "module" NOT IN ('dashboard','leads','contacts','accounts','deals','tasks','campaigns','workflows','forms','products','custom_fields','archived_data','users','groups','roles','settings');
UPDATE "RolePermission" SET "canView" = false WHERE "module" NOT IN ('dashboard','leads','contacts','accounts','deals','tasks','campaigns','workflows','forms','products','custom_fields','archived_data','users','groups','roles','settings');
UPDATE "RolePermission" SET "canCreate" = false WHERE "module" NOT IN ('leads','contacts','accounts','deals','tasks','campaigns','workflows','forms','products','custom_fields','users','groups','roles');
UPDATE "RolePermission" SET "canEdit" = false WHERE "module" NOT IN ('leads','contacts','accounts','deals','tasks','campaigns','workflows','forms','products','custom_fields','users','groups','roles','settings');
UPDATE "RolePermission" SET "canDelete" = false WHERE "module" NOT IN ('forms','groups');
UPDATE "RolePermission" SET "canArchive" = false WHERE "module" NOT IN ('leads','contacts','accounts','deals','tasks','campaigns','workflows','products','users','roles');
UPDATE "RolePermission" SET "canImport" = false WHERE "module" NOT IN ('leads','contacts','accounts');
UPDATE "RolePermission" SET "canManageStages" = false WHERE "module" NOT IN ('deals');
UPDATE "RolePermission" SET "canComplete" = false WHERE "module" NOT IN ('tasks');
UPDATE "RolePermission" SET "canAssign" = false WHERE "module" NOT IN ('tasks','roles');
UPDATE "RolePermission" SET "canSend" = false WHERE "module" NOT IN ('campaigns');
UPDATE "RolePermission" SET "canDuplicate" = false WHERE "module" NOT IN ('campaigns','workflows','forms');
UPDATE "RolePermission" SET "canViewReports" = false WHERE "module" NOT IN ('campaigns');
UPDATE "RolePermission" SET "canActivate" = false WHERE "module" NOT IN ('workflows','users');
UPDATE "RolePermission" SET "canViewRuns" = false WHERE "module" NOT IN ('workflows');
UPDATE "RolePermission" SET "canPublish" = false WHERE "module" NOT IN ('forms');
UPDATE "RolePermission" SET "canViewSubmissions" = false WHERE "module" NOT IN ('forms');
UPDATE "RolePermission" SET "canViewClosedWon" = false WHERE "module" NOT IN ('products');
UPDATE "RolePermission" SET "canDisable" = false WHERE "module" NOT IN ('custom_fields');
UPDATE "RolePermission" SET "canRestore" = false WHERE "module" NOT IN ('archived_data');
UPDATE "RolePermission" SET "canView" = true WHERE "canCreate" OR "canEdit" OR "canDelete" OR "canArchive" OR "canImport" OR "canManageStages" OR "canComplete" OR "canAssign" OR "canSend" OR "canDuplicate" OR "canViewReports" OR "canActivate" OR "canViewRuns" OR "canPublish" OR "canViewSubmissions" OR "canViewClosedWon" OR "canDisable" OR "canRestore";

-- The protected administrator has every applicable flag, including new actions.
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':dashboard'), r."tenantId", r."id", 'dashboard',true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':leads'), r."tenantId", r."id", 'leads',true,true,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':contacts'), r."tenantId", r."id", 'contacts',true,true,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':accounts'), r."tenantId", r."id", 'accounts',true,true,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':deals'), r."tenantId", r."id", 'deals',true,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':tasks'), r."tenantId", r."id", 'tasks',true,true,true,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':campaigns'), r."tenantId", r."id", 'campaigns',true,true,true,false,true,false,false,false,false,true,true,true,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':workflows'), r."tenantId", r."id", 'workflows',true,true,true,false,true,false,false,false,false,false,true,false,true,true,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':forms'), r."tenantId", r."id", 'forms',true,true,true,true,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':products'), r."tenantId", r."id", 'products',true,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':custom_fields'), r."tenantId", r."id", 'custom_fields',true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':archived_data'), r."tenantId", r."id", 'archived_data',true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':users'), r."tenantId", r."id", 'users',true,true,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':groups'), r."tenantId", r."id", 'groups',true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':roles'), r."tenantId", r."id", 'roles',true,true,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
INSERT INTO "RolePermission" ("id","tenantId","roleId","module","canView","canCreate","canEdit","canDelete","canArchive","canImport","canManageStages","canComplete","canAssign","canSend","canDuplicate","canViewReports","canActivate","canViewRuns","canPublish","canViewSubmissions","canViewClosedWon","canDisable","canRestore")
SELECT md5(r."id" || ':settings'), r."tenantId", r."id", 'settings',true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false FROM "RoleDefinition" r WHERE r."name" = 'Client Admin' AND r."isSystemRole" = true
ON CONFLICT ("roleId","module") DO UPDATE SET "canView" = EXCLUDED."canView","canCreate" = EXCLUDED."canCreate","canEdit" = EXCLUDED."canEdit","canDelete" = EXCLUDED."canDelete","canArchive" = EXCLUDED."canArchive","canImport" = EXCLUDED."canImport","canManageStages" = EXCLUDED."canManageStages","canComplete" = EXCLUDED."canComplete","canAssign" = EXCLUDED."canAssign","canSend" = EXCLUDED."canSend","canDuplicate" = EXCLUDED."canDuplicate","canViewReports" = EXCLUDED."canViewReports","canActivate" = EXCLUDED."canActivate","canViewRuns" = EXCLUDED."canViewRuns","canPublish" = EXCLUDED."canPublish","canViewSubmissions" = EXCLUDED."canViewSubmissions","canViewClosedWon" = EXCLUDED."canViewClosedWon","canDisable" = EXCLUDED."canDisable","canRestore" = EXCLUDED."canRestore";
COMMIT;
