import React from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
const product = { id: '0ff82f9c-48e9-4e1c-8c77-8a30755d704c', name: 'CCTV', dealValue: 5000 };
vi.mock('@/store/DataContext', () => ({ useData: () => ({ pipelines: [{ id: 'pipeline', name: 'Sales Pipeline', stages: [{ id: 'stage', name: 'Lead' }] }] }) }));
vi.mock('@/shared/hooks/use-product-interests', () => ({ useProductInterests: () => ({ products: [product], loading: false, error: '' }) }));
vi.mock('@/shared/hooks/use-permissions', () => ({ useHasPermission: () => true }));
vi.mock('./deal-account-field', () => ({ DealAccountField: () => null }));
vi.mock('./deal-contacts-field', () => ({ DealContactsField: () => null }));
vi.mock('./deal-leads-field', () => ({ DealLeadsField: () => null }));
vi.mock('@/shared/components/entity-combobox', () => ({ EntityCombobox: () => null }));
import { DealForm } from './deal-form';
afterEach(cleanup);
it('requires a catalog product and submits its ID array without a manual value', async () => {
  const save = vi.fn().mockResolvedValue(undefined);
  render(<DealForm mode="create" preselect={{ pipelineId: 'pipeline', stageId: 'stage' }} onSubmit={save} onCancel={() => {}} />);
  const selector = screen.getByRole('button', { name: 'Product Interest' });
  const amount = screen.getByLabelText('Value') as HTMLInputElement;
  expect(amount.readOnly).toBe(true);
  fireEvent.change(screen.getByLabelText(/Title/), { target: { value: 'Installation' } });
  expect((screen.getByRole('button', { name: 'Create Deal' }) as HTMLButtonElement).disabled).toBe(true);
  fireEvent.click(selector);
  fireEvent.click(screen.getByRole('checkbox', { name: 'CCTV' }));
  expect(amount.value).toBe('5,000.00');
  expect((screen.getByRole('checkbox', { name: 'CCTV' }) as HTMLInputElement).checked).toBe(true);
  expect(screen.getByText('Product Interests').closest('.space-y-4')?.textContent).toContain('Deal Information');
  fireEvent.click(screen.getByRole('checkbox', { name: 'CCTV' }));
  expect(amount.value).toBe('0.00');
  fireEvent.click(screen.getByRole('checkbox', { name: 'CCTV' }));
  fireEvent.keyDown(screen.getByRole('group', { name: 'Product interests' }), { key: 'Escape' });
  await waitFor(() => expect((screen.getByRole('button', { name: 'Create Deal' }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Create Deal' }));
  await waitFor(() => expect(save).toHaveBeenCalledWith(expect.objectContaining({ productInterestIds: [product.id], value: undefined, productInterests: undefined, currency: 'PHP' })));
});
it('keeps a historical Deal value when the catalog price is different', () => {
  render(<DealForm mode="edit" initialData={{ title: 'History', value: 1200, productInterestId: product.id, productInterests: ['CCTV'] }} onSubmit={vi.fn()} onCancel={() => {}} />);
  expect((screen.getByLabelText('Value') as HTMLInputElement).value).toBe('1,200.00');
  expect((screen.getByLabelText('Value') as HTMLInputElement).readOnly).toBe(true);
});
